export interface IGetLensListRequest {
  company_code: string;
  id_lokasi: string;
  status?: string;
  reset_redis?: string;
}

export class GetLensListRequest {
  company_code: string;
  id_lokasi: string;
  status?: string;
  reset_redis?: string;

  constructor(req: IGetLensListRequest) {
    this.company_code = req.company_code;
    this.id_lokasi = req.id_lokasi;
    this.status = req.status ?? '1';
    this.reset_redis = req.reset_redis ?? '1';
  }

  static createFromJson(json: IGetLensListRequest) {
    return new GetLensListRequest(json);
  }
}

export interface IUpdateOKCatatanKeperawatanPra {
  suhu: string;
  nadi: string;
  rr: string;
  td: string;
  tb: string;
  bb: string;
  t: string;
  sat: string;
  skala_nyeri: string;
  status_mental: string[];
  riwayat_penyakit: string;
  riwayat_penyakit_keterangan: string;
  pengobatan_saat_ini: string;
  pengobatan_saat_ini_keterangan: string;
  alat_bantu:  string
  alat_bantu_keterangan: string;
  operasi_sebelumnya: string;
  operasi_sebelumnya_keterangan: string;
  operasi_sebelumnya_tanggal: string;
  operasi_sebelumnya_di: string;
  alergi: string;
  alergi_keterangan: string;
  pemeriksaan_penunjang: string[];
  pemeriksaan_penunjang_keterangan: string;
  verifikasi_periksa_identitas: string;
  verifikasi_periksa_identitas_keterangan: string;
  verifikasi_periksa_identitas_rajal_keterangan: string;
  verifikasi_periksa_gelang: string;
  verifikasi_periksa_gelang_keterangan: string;
  verifikasi_periksa_gelang_rajal_keterangan: string;
  verifikasi_surat_pengantar_operasi: string;
  verifikasi_surat_pengantar_operasi_keterangan: string;
  verifikasi_surat_pengantar_operasi_rajal_keterangan: string;
  verifikasi_jenis_lokasi_operasi: string;
  verifikasi_jenis_lokasi_operasi_keterangan: string;
  verifikasi_jenis_lokasi_operasi_rajal_keterangan: string;
  verifikasi_masalah_bahasa_komunikasi: string;
  verifikasi_masalah_bahasa_komunikasi_keterangan: string;
  verifikasi_masalah_bahasa_komunikasi_rajal_keterangan: string;
  verifikasi_surat_izin_operasi: string;
  verifikasi_surat_izin_operasi_keterangan: string;
  verifikasi_surat_izin_operasi_rajal_keterangan: string;
  verifikasi_persetujuan_anestesi: string;
  verifikasi_persetujuan_anestesi_keterangan: string;
  verifikasi_persetujuan_anestesi_rajal_keterangan: string;
  verifikasi_kelengkapan_resume_medis: string;
  verifikasi_kelengkapan_resume_medis_keterangan: string;
  verifikasi_kelengkapan_resume_medis_rajal_keterangan: string;
  verifikasi_kelengkapan_x_ray: string;
  verifikasi_kelengkapan_x_ray_keterangan: string;
  verifikasi_kelengkapan_x_ray_rajal_keterangan: string;
  persiapan_puasa: string;
  persiapan_puasa_keterangan: string;
  persiapan_puasa_rajal_keterangan: string;
  persiapan_prothese_luar: string;
  persiapan_prothese_luar_keterangan: string;
  persiapan_prothese_luar_rajal_keterangan: string;
  persiapan_prothese_dalam: string;
  persiapan_prothese_dalam_keterangan: string;
  persiapan_prothese_dalam_rajal_keterangan: string;
  persiapan_penjepit_rambut: string;
  persiapan_penjepit_rambut_keterangan: string;
  persiapan_penjepit_rambut_rajal_keterangan: string;
  persiapan_kulit: string;
  persiapan_kulit_keterangan: string;
  persiapan_kulit_rajal_keterangan: string;
  persiapan_alat_bantu: string;
  persiapan_alat_bantu_keterangan: string;
  persiapan_alat_bantu_rajal_keterangan: string;
  persiapan_obat_disertakan: string;
  persiapan_obat_disertakan_keterangan: string;
  persiapan_obat_disertakan_rajal_keterangan: string;
  persiapan_obat_terakhir_diberikan: string;
  persiapan_obat_terakhir_diberikan_keterangan: string;
  persiapan_obat_terakhir_diberikan_rajal_keterangan: string;
  persiapan_vaskuler_akses: string;
  persiapan_vaskuler_akses_keterangan: string;
  persiapan_vaskuler_akses_rajal_keterangan: string;
  lain_site_marking: string;
  lain_penjelasan_singkat: string;
  tanggal: string;
  "ttd-perawat-ruangan": string;
  "id-perawat-ruangan": string;
  "ttd-perawat-penerima": string;
  "id-perawat-penerima":  string;
}

export interface IUpdateInstruksiPascaBedahRajal {
  keluhan_rumah: string
  terjadi_rumah: string
  mobilisasi: string
  anjuran_kendaraan: string
  anjuran_alat_berat: string
  anjuran_alkohol: string
  anjuran_ekstremitas: string
  anjuran_obat: string
  anjuran_lain: string
  anjuran_lain_teks: string
  anjuran_terkena: string
  anjuran_tidur_eyeshield: string;
  anjuran_tidur_telentang: string
  anjuran_tidur_telungkup: string
  anjuran_tidur_membungkuk: string
  anjuran_tidur_dll: string
  anjuran_tidur_lain_teks: string
  pendamping_keluarga: string
  pendamping_keluarga_teks: string
  pendamping_medis: string
  pendamping_lain: string
  pendamping_lain_teks: string
  nomor_dihubungi: string
  jadwal_kontrol: string
  lain_lain: string
  ttd_pasien: string
  ttd_dpjp: string
  id_dpjp: string
  nomor_mr: string
  id_pelayanan: string
  kode_cabang: string
  tipe_pasien: string
  jenis_pelayanan: string
  id_dokter: string
  no_sep: string
}

export interface IUpdateSurveilansInfeksiHais {
  jenis_operasi: string
  asa_score: string
  jenis_anestesi: string
  dokter_anestesi: string
  kelembaban_udara: string
  suhu_ruangan: string
  komplikasi_saat_operasi: string
  indikator_instrumen: string
  disinfeksi_kulit: string
  jahitan: string
  profilaksis: string
  profilaksis_nama_obat: string
  profilaksis_dosis: string
  profilaksis_jam_beri_obat: string
  antibiotik_tambahan: string
  antibiotik_tambahan_nama_obat: string
  antibiotik_tambahan_dosis: string
  antibiotik_tambahan_jam_beri_obat: string
  implant: string
  sterilisasi_cssd: string
  dokter_operasi: string
  asisten_operasi: string
  urutan_operasi: string
  kualifikasi_dokter_bedah: string
  lama_operasi: string
  jumlah_staf_operasi: string
  ruang_operasi: string
  klasifikasi_luka: string
  prosedur_operasi: string
  diagnosa_akhir: string
  tanggal_keluar: string
  cara_pulang_pasien: string
  cara_pulang_pasien_pindah_rs_tujuan: string
  hais_ttd_perawat: string
  hais_id_perawat: string
  hais_ttd_ipcn: string
  hais_id_ipcn: string
  nomor_mr: string
  id_pelayanan: string
  kode_cabang: string
  tipe_pasien: string
  jenis_pelayanan: string
  id_dokter: string
  no_sep: string
}

export interface IUpdateAsesmenPraOperasi {
  td: string
  nadi: string
  rr: string
  suhu: string
  skala_nyeri: string
  alergi: string
  alergi_keterangan: string
  penyakit_peserta: string[]
  penyakit_peserta_keterangan: string
  pengobatan_saat_ini: string[]
  pengobatan_saat_ini_lain: string
  tonometri: string
  biometri: string
  usg_mata: string
  foto_fundus: string
  oct_makula: string
  dll: string
  hasil_konsultasi: string
  persediaan_darah: string
  persetujuan: string
  anestesi: string
  jenis_kasus: string
  diagnosa: string
  rencana_operasi: string
  tanggal_operasi: string
  ahli_bedah: string
  tanggal: string
  ttd_dokter: string
  id_dokter: string
  id_dokter_ttd: string;
  nomor_mr: string
  id_pelayanan: string
  kode_cabang: string
  tipe_pasien: string
  jenis_pelayanan: string
  no_sep: string
}

export interface IUpdateStatusAnestesi {
  id_dpjp_anestesi: string;
  id_asisten_anestesi: string;
  id_dpjp_bedah: string;
  diagnosa_pra_bedah: string;
  jenis_pembedahan: string;
  diagnosis_pasca_bedah: string;
  teknik_anestesi: string;
  teknik_anestesi_lainnya: string;
  teknik_khusus_hipotensi: string;
  teknik_khusus_bronkoskopi: string;
  teknik_khusus_tci: string;
  teknik_khusus_glidescope: string;
  teknik_khusus_cpb: string;
  teknik_khusus_usg: string;
  teknik_khusus_ventilasi: string;
  teknik_khusus_stimulator: string;
  teknik_khusus_lainnya: string;
  teknik_khusus_lainnya_teks: string;
  monitoring_ekg: string;
  monitoring_ekg_teks: string;
  monitoring_nibp: string;
  monitoring_cath: string;
  monitoring_arteri: string;
  monitoring_arteri_teks: string;
  monitoring_ngt: string;
  monitoring_spo2: string;
  monitoring_etco2: string;
  monitoring_bis: string;
  monitoring_katerer: string;
  monitoring_stetoskop: string;
  monitoring_cvp: string;
  monitoring_cvp_teks: string;
  monitoring_temp: string;
  monitoring_lainnya: string;
  monitoring_lainnya_teks: string;
  image_1: string;
  image_2: string;
  image_3: string;
  asa: string;
  alergi: string;
  alergi_keterangan: string;
  penyulit_pra_anestesi: string;
  checklist_inform_consent: string;
  checklist_monitoring: string;
  checklist_obat_anestesi: string;
  checklist_obat_emergensi: string;
  checklist_tatalaksana: string;
  checklist_suction: string;
  checklist_mesin: string;
  jam_pra_induksi: string;
  pra_induksi_kesadaran: string;
  pra_induksi_tekanan_darah: string;
  pra_induksi_denyut_nadi: string;
  pra_induksi_rr: string;
  pra_induksi_suhu: string;
  pra_induksi_saturasi: string;
  pra_induksi_lainnya: string;
  catatan: string;
  infus_perifer_1: string;
  infus_perifer_2: string;
  infus_perifer_3: string;
  posisi: string;
  posisi_lainnya: string;
  premedikasi_oral: string;
  premedikasi_im: string;
  premedikasi_iv: string;
  induksi_intravena: string;
  induksi_inhalasi: string;
  face_mask_no: string;
  oro_no: string;
  ett_no: string;
  ett_jenis: string;
  ett_fiksasi: string;
  lma_no: string;
  lma_jenis: string;
  trakhesotomi: string;
  bronkoskopi_fiber: string;
  glidescope: string;
  tata_laksana_lainnya: string;
  intubasi_sesudah_tidur: string;
  intubasi_blind: string;
  intubasi_oral: string;
  intubasi_nasal: string;
  intubasi_kanan: string;
  intubasi_kiri: string;
  intubasi_trakheostomi: string;
  intubasi_sulit_ventilasi: string;
  intubasi_sulit_ventilasi_teks: string;
  intubasi_sulit_intubasi: string;
  intubasi_sulit_intubasi_teks: string;
  intubasi_dengan_stilet: string;
  intubasi_dengan_stilet_teks: string;
  intubasi_cuff: string;
  intubasi_level_ett: string;
  intubasi_pack: string;
  ventilasi_spontan: string;
  ventilasi_kendali: string;
  ventilasi_ventilator: string;
  ventilasi_ventilator_tv: string;
  ventilasi_ventilator_rr: string;
  ventilasi_ventilator_peep: string;
  ventilasi_lainnya: string;
  ventilasi_lainnya_teks: string;
  ckp_jam_masuk: string;
  ckp_tekanan_darah: string;
  ckp_denyut_nadi: string;
  ckp_rr: string;
  ckp_suhu: string;
  ckp_kesadaran: string;
  ckp_pernafasan: string;
  ckp_penyulit_intra_operatif: string;
  ckp_instruksi_khusus: string;
  json_image_chart: string;
  url_image_chart: string;
  name_image_chart: string;
  size_image_chart: string;
  type_image_chart: string;
  skala_anestesi: string;
  vas: string;
  vas_pulih: string;
  jam_keluar_pulih: string;
  aldrette_aktivitas: string;
  aldrette_sirkulasi: string;
  aldrette_pernafasan: string;
  aldrette_kesadaran: string;
  aldrette_warna_kulit: string;
  aldrette_total: string;
  aldrette_skor_vas: string;
  steward_pernafasan: string;
  steward_kesadaran: string;
  steward_motorik: string;
  steward_total: string;
  steward_skor_vas: string;
  pindah_ke: string;
  pindah_ke_lainnya: string;
  catatan_khusus_ruang_pemulihan: string;
  ipa_pengelolaan_nyeri: string;
  ipa_penanganan_mual: string;
  ipa_antibiotik: string;
  ipa_obat: string;
  ipa_infus: string;
  ipa_diet: string;
  ipa_tensi_setiap: string;
  ipa_tensi_selama: string;
  ipa_lainnya: string;
  ttd_penata_anestesi: string;
  id_penata_anestesi: string;
  ttd_dokter_anestesi: string;
  id_dokter_anestesi: string;
}

export interface IUpdatePersiapanPeralatan {
  unit: string;
  tanggal_tindakan: string;
  jenis_operasi: string;
  teknik_anestesi: string;
  listrik_1: string;
  listrik_2: string;
  listrik_3: string;
  gas_1: string;
  gas_2: string;
  gas_3: string;
  gas_4: string;
  gas_5: string;
  gas_6: string;
  mesin_anestesi_1: string;
  mesin_anestesi_2: string;
  mesin_anestesi_3: string;
  mesin_anestesi_4: string;
  mesin_anestesi_5: string;
  manajemen_nafas_1: string;
  manajemen_nafas_2: string;
  manajemen_nafas_3: string;
  manajemen_nafas_4: string;
  manajemen_nafas_5: string;
  manajemen_nafas_6: string;
  manajemen_nafas_7: string;
  manajemen_nafas_8: string;
  manajemen_nafas_9: string;
  pemantauan_1: string;
  pemantauan_2: string;
  pemantauan_3: string;
  pemantauan_4: string;
  pemantauan_5: string;
  pemantauan_6: string;
  lainnya_1: string;
  lainnya_2: string;
  lainnya_3: string;
  lainnya_4: string;
  lainnya_5: string;
  lainnya_6: string;
  lainnya_7: string;
  obat_1: string;
  obat_2: string;
  obat_3: string;
  obat_4: string;
  obat_5: string;
  obat_6: string;
  obat_7: string;
  obat_7_teks: string;
  ttd_penata_anestesi: string;
  id_penata_anestesi: string;
  ttd_dokter_anestesi: string;
  id_dokter_anestesi: string;
}

