export interface IUpdatePengkajianAwalKeperawatanDewasa {
  skrining_nyeri: string;
  provocating: string;
  quality: string;
  region: string;
  severity: string;
  time: string;
  tanggal_masuk_rawat_inap: string
  riwayat_alergi_tidak_check: string
  riwayat_alergi_obat_check: string;
  riwayat_alergi_makanan_check: string;
  riwayat_alergi_lainnya_check: string;
  riwayat_alergi_klip_tanda_check: string;
  riwayat_alergi_tidak_diketahui_check: string;
  riwayat_alergi_obat_keterangan: string
  riwayat_alergi_obat_reaksi: string
  riwayat_alergi_makanan_keterangan: string
  riwayat_alergi_makanan_reaksi: string
  riwayat_alergi_lainnya_keterangan: string
  riwayat_alergi_lainnya_reaksi: string
  keluhan_utama: string
  riwayat_pengobatan_sebelumnya: string
  pernah_dirawat: string
  pernah_dirawat_keterangan: string
  implant_terpasang: string
  implant_terpasang_keterangan: string
  psikologis: string
  psikologis_lain_keterangan: string
  mental: string
  mental_lain_keterangan: string
  mental_kekerasan_keterangan: string
  hubungan_pasien_keluarga: string
  tempat_tinggal: string
  tempat_tinggal_keterangan: string
  kerabat_nama: string
  kerabat_hubungan: string
  kerabat_telepon: string
  agama: string
  spiritual_nilai_nilai: string
  spiritual_keyakinan: string;
  spiritual_kegiatan_perawatan: string
  td: string
  bb: string
  p: string
  nadi: string
  tb: string
  suhu: string
  rpt: string
  rpo: string
  "gambar-mata-od": string
  "gambar-mata-os": string
  nutrisi_turun_bb: string
  asupan_makan: string
  diagnosa_khusus: string
  diagnosa: string
  jenis_penyakit: string[]
  jenis_penyakit_keterangan: string
  nutrisionis: string
  nutrisionis_tanggal: string
  risiko_jatuh: string
  status_fungsional: string
  status_fungsional_keterangan: string
  alat_bantu_jalan: string
  skala_nyeri: string
  lokasi_nyeri: string
  intensitas_istirahat: string
  jenis_nyeri: string
  intensitas_aktivitas: string
  nyeri_hilang: string[]
  hambatan: string
  jenis_hambatan: string[]
  jenis_hambatan_lain_keterangan: string
  topik_pembelajaran: string[]
  topik_pembelajaran_lain_keterangan: string
  waktu_penilaian: string
  keperawatan_1_check: string;
  keperawatan_2_check: string;
  keperawatan_3_check: string;
  keperawatan_4_check: string;
  keperawatan_5_check: string;
  keperawatan_6_check: string;
  keperawatan_7_check: string;
  keperawatan_8_check: string;
  keperawatan_9_check: string;
  masalah_keperawatan_lainnya_text: string;
  rencana_keperawatan_lainnya_text: string;
  tanggal_pengkajian_masuk: string
  tanggal_pengkajian_keluar: string
  "ttd-perawat-pengkajian-masuk": string
  "id-perawat-pengkajian-masuk": string
  "ttd-perawat-pengkajian-keluar": string
  "id-perawat-pengkajian-keluar": string
  sebelum_sakit_makan: string;
  sebelum_sakit_mandi: string;
  sebelum_sakit_perawatan_diri: string;
  sebelum_sakit_berpakaian: string;
  sebelum_sakit_bak: string;
  sebelum_sakit_bab: string;
  sebelum_sakit_penggunaan_toilet: string;
  sebelum_sakit_transfer: string;
  sebelum_sakit_mobilitas: string;
  sebelum_sakit_naik_turun_tangga: string;
  saat_masuk_makan: string;
  saat_masuk_mandi: string;
  saat_masuk_perawatan_diri: string;
  saat_masuk_berpakaian: string;
  saat_masuk_bak: string;
  saat_masuk_bab: string;
  saat_masuk_penggunaan_toilet: string;
  saat_masuk_transfer: string;
  saat_masuk_mobilitas: string;
  saat_masuk_naik_turun_tangga: string;
  minggu_2_makan: string;
  minggu_2_mandi: string;
  minggu_2_perawatan_diri: string;
  minggu_2_berpakaian: string;
  minggu_2_bak: string;
  minggu_2_bab: string;
  minggu_2_penggunaan_toilet: string;
  minggu_2_transfer: string;
  minggu_2_mobilitas: string;
  minggu_2_naik_turun_tangga: string;
  minggu_3_makan: string;
  minggu_3_mandi: string;
  minggu_3_perawatan_diri: string;
  minggu_3_berpakaian: string;
  minggu_3_bak: string;
  minggu_3_bab: string;
  minggu_3_penggunaan_toilet: string;
  minggu_3_transfer: string;
  minggu_3_mobilitas: string;
  minggu_3_naik_turun_tangga: string;
  minggu_4_makan: string;
  minggu_4_mandi: string;
  minggu_4_perawatan_diri: string;
  minggu_4_berpakaian: string;
  minggu_4_bak: string;
  minggu_4_bab: string;
  minggu_4_penggunaan_toilet: string;
  minggu_4_transfer: string;
  minggu_4_mobilitas: string;
  minggu_4_naik_turun_tangga: string;
  saat_pulang_makan: string;
  saat_pulang_mandi: string;
  saat_pulang_perawatan_diri: string;
  saat_pulang_berpakaian: string;
  saat_pulang_bak: string;
  saat_pulang_bab: string;
  saat_pulang_penggunaan_toilet: string;
  saat_pulang_transfer: string;
  saat_pulang_mobilitas: string;
  saat_pulang_naik_turun_tangga: string;
  sebelum_sakit_total: string;
  saat_masuk_total: string;
  minggu_2_total: string;
  minggu_3_total: string;
  minggu_4_total: string;
  saat_pulang_total: string;
  nomor_mr: string
  id_pelayanan: string
  kode_cabang: string
  tipe_pasien: string
  jenis_pelayanan: string
  id_dokter: string
  no_sep: string
}

export interface IUpdatePengkajianAwalKeperawatanAnak {
  tanggal: string;
  jam: string;
  pengkajian_diperoleh: string | null;
  keluhan_utama: string;
  riwayat_penyakit_sekarang: string;
  riwayat_penyakit_dahulu: string;
  riwayat_pengobatan: string;
  riwayat_operasi_radio: string | null;
  riwayat_operasi_ya_teks: string;
  riwayat_penyakit_hipertensi: string;
  riwayat_penyakit_asma: string;
  riwayat_penyakit_diabetes: string;
  riwayat_penyakit_hepatitis: string;
  riwayat_penyakit_glaukoma: string;
  riwayat_penyakit_stroke: string;
  riwayat_penyakit_lainnya: string;
  riwayat_penyakit_lainnya_teks: string;
  lama_kehamilan: string;
  komplikasi_radio: string | null;
  komplikasi_radio_ket: string;
  neonatus_radio: string | null;
  neonatus_radio_ket: string;
  maternal_radio: string | null;
  maternal_radio_ket: string;
  imunisasi_bcg: string;
  imunisasi_polio_1: string;
  imunisasi_polio_2: string;
  imunisasi_polio_3: string;
  imunisasi_hepatitis_1: string;
  imunisasi_hepatitis_2: string;
  imunisasi_hepatitis_3: string;
  imunisasi_varicela: string;
  imunisasi_dpt_1: string;
  imunisasi_dpt_2: string;
  imunisasi_dpt_3: string;
  imunisasi_typhus: string;
  imunisasi_campak: string;
  imunisasi_mmr: string;
  imunisasi_lainnya_2: string;
  imunisasi_lainnya_2_teks: string;
  imunisasi_influenza: string;
  imunisasi_lainnya_1: string;
  imunisasi_lainnya_1_teks: string;
  bb_lahir: string;
  pb_lahir: string;
  asi_umur: string;
  makan_tambahan_umur: string;
  berjalan_umur: string;
  tengkurap_umur: string;
  duduk_umur: string;
  merangkak_umur: string;
  berdiri_umur: string;
  asesmen_remaja_1: string | null;
  asesmen_remaja_2: string | null;
  asesmen_remaja_3: string | null;
  asesmen_remaja_4: string | null;
  asesmen_remaja_5: string | null;
  asesmen_remaja_6: string | null;
  asesmen_remaja_7: string | null;
  asesmen_remaja_8: string | null;
  asesmen_remaja_9: string | null;
  asesmen_remaja_10: string | null;
  asesmen_remaja_11: string | null;
  asesmen_remaja_12: string | null;
  pf_td: string;
  pf_nadi: string;
  pf_suhu: string;
  pf_bb: string;
  pf_p: string;
  pf_tb: string;
  kesadaran_radio: string | null;
  alergi_reaksi_radio: string | null;
  nyeri_radio: string | null;
  pengkajian_nyeri: string | null;
  wajah_radio: string | null;
  kaki_radio: string | null;
  aktivitas_radio: string | null;
  menangis_radio: string | null;
  kenyamanan_radio: string | null;
  penyebab_nyeri: string;
  kualitas_nyeri: string;
  lokasi_nyeri: string;
  skala_nyeri: string;
  durasi_nyeri: string;
  total_skor: string;
  kategori_nyeri: string;
  skala_nyeri_radio: string | null;
  skrining_gizi_1: string | null;
  skrining_gizi_2: string | null;
  skrining_gizi_3: string | null;
  skrining_gizi_4: string | null;
  skrining_gizi_total: string;
  kategori_nilai_gizi: string;
  keterbatasan_gerak_radio: string | null;
  nyeri_otot: string;
  kelemahan: string;
  kaku_otot: string;
  amputasi: string;
  lemah_otot: string;
  deformitas: string;
  nyeri_sendi: string;
  parese: string;
  parese_dibagian: string;
  bengkak_sendi: string;
  inkoordinasi: string;
  tidur_malam: string;
  tidur_siang: string;
  kesulitan_tidur_radio: string | null;
  sebelum_sakit_makan: string;
  sebelum_sakit_mandi: string;
  sebelum_sakit_perawatan_diri: string;
  sebelum_sakit_berpakaian: string;
  sebelum_sakit_bak: string;
  sebelum_sakit_bab: string;
  sebelum_sakit_penggunaan_toilet: string;
  sebelum_sakit_transfer: string;
  sebelum_sakit_mobilitas: string;
  sebelum_sakit_naik_turun_tangga: string;
  saat_masuk_makan: string;
  saat_masuk_mandi: string;
  saat_masuk_perawatan_diri: string;
  saat_masuk_berpakaian: string;
  saat_masuk_bak: string;
  saat_masuk_bab: string;
  saat_masuk_penggunaan_toilet: string;
  saat_masuk_transfer: string;
  saat_masuk_mobilitas: string;
  saat_masuk_naik_turun_tangga: string;
  minggu_2_makan: string;
  minggu_2_mandi: string;
  minggu_2_perawatan_diri: string;
  minggu_2_berpakaian: string;
  minggu_2_bak: string;
  minggu_2_bab: string;
  minggu_2_penggunaan_toilet: string;
  minggu_2_transfer: string;
  minggu_2_mobilitas: string;
  minggu_2_naik_turun_tangga: string;
  minggu_3_makan: string;
  minggu_3_mandi: string;
  minggu_3_perawatan_diri: string;
  minggu_3_berpakaian: string;
  minggu_3_bak: string;
  minggu_3_bab: string;
  minggu_3_penggunaan_toilet: string;
  minggu_3_transfer: string;
  minggu_3_mobilitas: string;
  minggu_3_naik_turun_tangga: string;
  minggu_4_makan: string;
  minggu_4_mandi: string;
  minggu_4_perawatan_diri: string;
  minggu_4_berpakaian: string;
  minggu_4_bak: string;
  minggu_4_bab: string;
  minggu_4_penggunaan_toilet: string;
  minggu_4_transfer: string;
  minggu_4_mobilitas: string;
  minggu_4_naik_turun_tangga: string;
  saat_pulang_makan: string;
  saat_pulang_mandi: string;
  saat_pulang_perawatan_diri: string;
  saat_pulang_berpakaian: string;
  saat_pulang_bak: string;
  saat_pulang_bab: string;
  saat_pulang_penggunaan_toilet: string;
  saat_pulang_transfer: string;
  saat_pulang_mobilitas: string;
  saat_pulang_naik_turun_tangga: string;
  sebelum_sakit_total: string;
  saat_masuk_total: string;
  minggu_2_total: string;
  minggu_3_total: string;
  minggu_4_total: string;
  saat_pulang_total: string;
  resiko_jatuh_radio: string | null;
  bicara_radio: string | null;
  perlu_penerjemah_radio: string | null;
  hambatan_belajar_radio: string | null;
  tingkat_pendidikan_radio: string | null;
  tingkat_pendidikan_lain_teks: string;
  status_ekonomi_radio: string | null;
  status_psikologi_tidak_terganggu: string;
  status_psikologi_cemas: string;
  status_psikologi_takut: string;
  status_psikologi_marah: string;
  status_psikologi_panik: string;
  status_mental_radio: string | null;
  sosial_radio: string | null;
  agama: string;
  keyakinan: string;
  nilai_nilai: string;
  spiritual: string;
  selama_keperawatan: string;
  keperawatan_persepsi_sensori: string;
  keperawatan_penurunan_kesadaran: string;
  keperawatan_nyeri: string;
  keperawatan_resiko_infeksi: string;
  keperawatan_intake_output: string;
  keperawatan_resiko_jatuh: string;
  keperawatan_hiperthermia: string;
  keperawatan_tekanan_intra: string;
  keperawatan_kurang_pengetahuan: string;
  keperawatan_lainnya: string;
  keperawatan_lainnya_masalah: string;
  keperawatan_lainnya_rencana: string;
  id_perawat_pengkaji: string;
  nama_perawat_pengkaji: string;
  ttd_perawat_pengkaji: string
}

export interface IUpdateEarlyWarningScoring {
  tanggal_konsul: string
  tipe_ews: string;
  rr: string
  score_rr: string
  perilaku: string;
  score_perilaku: string;
  kardiovaskular: string;
  score_kardiovaskular: string;
  nadi: string
  score_nadi: string
  td: string
  td_1: string;
  score_td: string
  suhu: string
  score_suhu: string
  tk: string
  score_tk: string
  total_skor: string
  keterangan: string
  unit_pengkaji: string
}

export interface IUpdateRencanaPemulanganPasien {
  edukasi_kesehatan: string;
  edukasi_kesehatan_keterangan: string;
  keterampilan_khusus: string;
  keterampilan_khusus_keterangan: string;
  jadwal_kontrol: string;
  jadwal_kontrol_keterangan: string;
  obat_pulang_check: string;
  obat_pulang_waktu: string;
  obat_pulang_keterangan: string;
  surat_kontrol_check: string;
  surat_kontrol_waktu: string;
  surat_kontrol_keterangan: string;
  id_perawat_pengkaji: string;
  tanda_tangan_perawat_pengkaji: string;
  tanda_tangan_pasien: string;
  pasien_dm: string
  pasien_dpjp: string
  waktu_masuk_rs: string
  pasien_alasan: string
  pasien_perawat: string
  pasien_tanggal: string
  pasien_discharge: string
  pasien_estimasi: string
  keterangan_pasien: string
  keterangan_pekerjaan: string
  keterangan_keuangan: string
  keterangan_antisipasi: string
  keterangan_antisipasi_keterangan: string
  uraian_value: string[]
  keterangan_membantu_keperluan: string
  keterangan_membantu_keperluan_keterangan: string
  keterangan_tinggal_sendiri: string
  keterangan_tinggal_sendiri_keterangan: string
  keterangan_peralatan_sendiri: string
  keterangan_peralatan_sendiri_keterangan: string
  keterangan_alat_bantu_sendiri: string
  keterangan_alat_bantu_sendiri_keterangan: string
  keterangan_bantuan_khusus: string
  keterangan_bantuan_khusus_keterangan: string
  keterangan_bantuan_pribadi: string
  keterangan_bantuan_pribadi_keterangan: string
  keterangan_nyeri_kronis: string
  keterangan_nyeri_kronis_keterangan: string
}

export interface IUpdatePengkajianResikoJatuhAnak {
  ttd_petugas: string
  petugas: string;
  waktu_pengkajian: string
  usia: string
  jenis_kelamin: string
  diagnosa: string
  gangguan_kognitif: string
  faktor_lingkungan: string
  respon_operasi: string
  penggunaan_obat: string
  keterangan_waktu_pengkajian: string
  total_skor: string
  resiko_jatuh: string
  resiko_jatuh_keterangan: string
  nomor_mr: string
  id_pelayanan: string
  kode_cabang: string
  tipe_pasien: string
  jenis_pelayanan: string
  id_dokter: string
  no_sep: string
  unit_pengkaji: string
  usia_radio: string;
  jenis_kelamin_radio: string;
  diagnosa_radio: string;
  gangguan_kognitif_radio: string;
  faktor_lingkungan_radio: string;
  respon_operasi_radio: string;
  penggunaan_obat_radio: string;
  ruangan: string;
  lembar: string;
}

export interface IImage {
  Url_Image: string;
  Name_Image: string;
  Size_Image: string;
  Type_Image: string;
}

export interface IUpdateCatatanMedisAwal {
  keluhan_utama: string
  anamnesa: string
  riwayat_penyakit_terdahulu: string
  riwayat_pemakaian_obat: string
  riwayat_penyakit_keluarga: string
  riwayat_pekerjaan: string;
  pekerjaan_zat_berbahaya: string
  pekerjaan_zat_berbahaya_keterangan: string
  riwayat_alergi: string
  kesadaran: string
  pernafasan: string
  tekanan_darah: string
  skala_nyeri: string
  nadi: string
  berat_badan: string
  cyanosis: string;
  suhu: string
  tinggi_badan: string
  keadaan_umum: string
  keadaan_gizi: string
  oedem: string
  ikterus: string
  pengkajian_kepala: string
  pengkajian_kepala_keterangan: string
  pengkajian_mata: string
  pengkajian_mata_keterangan: string
  pengkajian_tht: string
  pengkajian_tht_keterangan: string
  pengkajian_oedem: string
  pengkajian_oedem_keterangan: string
  pengkajian_mulut: string
  pengkajian_mulut_keterangan: string
  pengkajian_leher: string
  pengkajian_leher_keterangan: string
  pengkajian_jantung: string
  pengkajian_jantung_keterangan: string
  pengkajian_paru: string
  pengkajian_paru_keterangan: string
  pengkajian_dada: string
  pengkajian_dada_keterangan: string
  pengkajian_perut: string
  pengkajian_perut_keterangan: string
  pengkajian_urogenital: string
  pengkajian_urogenital_keterangan: string
  pengkajian_anggota_gerak: string
  pengkajian_anggota_gerak_keterangan: string
  pengkajian_status_neurologis: string
  pengkajian_status_neurologis_keterangan: string
  pengkajian_muskulos_keletal: string
  pengkajian_muskulos_keletal_keterangan: string
  pengkajian_palpebra_superior: string
  pengkajian_palpebra_superior_keterangan: string
  pengkajian_palpebra_inferior: string
  pengkajian_palpebra_inferior_keterangan: string
  pengkajian_conj_tarsal_superior: string
  pengkajian_conj_tarsal_superior_keterangan: string
  pengkajian_conj_tarsal_inferior: string
  pengkajian_conj_tarsal_inferior_keterangan: string
  pengkajian_conj_bulbi: string
  pengkajian_conj_bulbi_keterangan: string
  pengkajian_cornea: string
  pengkajian_cornea_keterangan: string
  pengkajian_coa: string
  pengkajian_coa_keterangan: string
  pengkajian_pupil: string
  pengkajian_pupil_keterangan: string
  pengkajian_iris: string
  pengkajian_iris_keterangan: string
  pengkajian_vitreous: string
  pengkajian_vitreous_keterangan: string
  pengkajian_lensa: string
  pengkajian_lensa_keterangan: string
  pengkajian_retina: string
  pengkajian_retina_keterangan: string
  pemeriksaan_penunjang: string
  pengkajian_posisi: string;
  pengkajian_posisi_keterangan: string;
  pengkajian_pergerakan: string;
  pengkajian_pergerakan_keterangan: string;
  pengkajian_funduscopy: string;
  pengkajian_funduscopy_keterangan: string;
  pengkajian_canthal_medial: string;
  pengkajian_canthal_medial_keterangan: string;
  pengkajian_canthal_lateral: string;
  pengkajian_canthal_lateral_keterangan: string;
  pengkajian_sclera: string;
  pengkajian_sclera_keterangan: string;
  diagnosa: string
  rencana_pengobatan: string
  tanggal: string;
  gambar_mata_od: string;
  gambar_mata_os: string;
  gambar_retina_od: string;
  gambar_retina_os: string;
  pediatrik: string;
  submit_pediatrik: string;
  submit_retina: string;
  data_objektif_lain: string;
  image_1: IImage,
  image_2: IImage,
  no_berobat: string;
  'nama-obat': Array<string>;
  'aturan-pakai': Array<string>;
  catatan: Array<string>;
  jumlah: Array<string>;
  "ttd-dokter": string
  "id-dokter": string
  nomor_mr: string
  id_pelayanan: string
  kode_cabang: string
  tipe_pasien: string
  jenis_pelayanan: string
  id_dokter: string
  no_sep: string
  cppt_id: string;
}

export interface IUpdatePengkajianResikoJatuhDewasa {
  ruangan: string;
  lembar: string;
  waktu_pengkajian: string
  riwayat_jatuh: string
  riwayat_jatuh_radio: string;
  diagnosa_sekunder: string
  diagnosa_sekunder_radio: string;
  alat_bantu_jalan: string;
  alat_bantu_jalan_radio: string;
  pasien_diinfus: string
  pasien_diinfus_radio: string;
  cara_berjalan: string
  cara_berjalan_radio: string;
  kondisi_mental: string
  kondisi_mental_radio: string;
  keterangan_waktu_pengkajian: string
  total_skor: string
  resiko_jatuh: string
  resiko_jatuh_keterangan: string
  nomor_mr: string
  id_pelayanan: string
  kode_cabang: string
  tipe_pasien: string
  jenis_pelayanan: string
  id_dokter: string
  no_sep: string
  unit_pengkaji: string
  ttd_perawat: string;
  id_perawat: string;
}

export interface IUpdateImplementasiPasienResikoJatuh {
  waktu_implementasi: string;
  pengkajian_awal_check: string;
  rem_tempat_tidur_check: string;
  dalam_jangkauan_check: string;
  tidak_menghalangi_check: string;
  palang_tempat_tidur_check: string;
  penanda_resiko_jatuh_check: string;
  libatkan_keluarga_check: string;
  cepat_menanggapi_check: string;
  memantau_respon_check: string;
  lakukan_pengkajian_ulang_check: string;
  ttd_perawat: string;
  id_perawat: string;
  unit_pengimplementasi: string;
}

export interface IUpdateAsesmenUlangTandaVital {
  waktu_asesmen: string;
  suhu: string;
  nadi: string;
  pernafasan: string;
  tekanan_darah: string;
  oxygen_saturation: string;
  th: string;
  skala_nyeri: string;
  lokasi_id: string;
  kualitas_id: string;
  frekuensi_id: string;
  tindakan_id: string;
  ttd_perawat: string;
  id_perawat: string;
}

export interface IUpdateInfeksiDaerahOperasi {
  id_pegawai: string;
  ttd_pegawai: string;
  hari: string
  waktu: string
  krs: string
  kontrol: string
  pelindung_kasa: string
  pelindung_eyeshield: string
  antibiotik_topikal: string
  antibiotik_oral: string
  mata_air: string
  mata_asap: string
  mata_debu: string
  gda: string
  ido_kabur: string
  ido_merah: string
  ido_nyeri: string
  ido_tio: string
  ido_odem_kornea: string
  ido_flare: string
  ido_hiporpion: string
  ido_membran: string
  ido_pupil: string
  ido_kekeruhan: string
  ido_kultur: string
  ido_dx: string
  keterangan: string
}

export interface IUpdateDpjp {
  pasien_kategori: string
  pasien_diagnosis: string
  ttd_dokter_utama: string
  dokter_utama: string
  ttd_dokter_ppds: string
  ppds: string
  sip: string
  ttd_dokter_ruangan: string
  dokter_ruangan: string
  tanggal_rawat_1: string
  ttd_dokter_dpjp_1: string
  dokter_dpjp_1: string
  tanggal_rawat_2: string
  ttd_dokter_dpjp_2: string
  dokter_dpjp_2: string
  tanggal_rawat_3: string
  ttd_dokter_dpjp_3: string
  dokter_dpjp_3: string
  tanggal_rawat_4: string
  ttd_dokter_dpjp_4: string
  dokter_dpjp_4: string
  tanggal_peralihan: string
  alasan_peralihan: string
  peralihan_dpjp: string
  ttd_dokter_peralihan: string
  dokter_peralihan: string
  nomor_mr: string
  id_pelayanan: string
  kode_cabang: string
  tipe_pasien: string
  jenis_pelayanan: string
  id_dokter: string
  no_sep: string
}

export interface IUpdateResumePasienPulang {
  tanggal_masuk: string
  tanggal_keluar: string
  diagnosa_masuk: string
  pasien_dirawat: string;
  anamnesa: string
  komorbiditas_1: string;
  komorbiditas_2: string;
  komorbiditas_3: string;
  komorbiditas_4: string;
  komorbiditas_5: string;
  pemeriksaan_fisik: string
  pemeriksaan_penunjang: string
  diagnosa_utama: string
  diagnosa_sekunder_1: string
  diagnosa_sekunder_2: string
  diagnosa_sekunder_3: string
  diagnosa_sekunder_4: string
  diagnosa_sekunder_5: string;
  mata: string;
  posisi_khusus: string;
  ruang_rawat: string;
  obat_rs: string
  tindakan: string
  kondisi_pulang: string
  anjuran: string
  obat_rumah: string
  tanggal: string
  tanda_tangan_pasien: string
  tanda_tangan_petugas: string
  id_ttd_petugas: string
  nomor_mr: string
  id_pelayanan: string
  kode_cabang: string
  tipe_pasien: string
  jenis_pelayanan: string
  id_dokter: string
  no_sep: string
}

export interface IUpdateFormulirPraAnestesi {
  status_perkawinan: string;
  pekerjaan: string;
  merokok_radio: string
  merokok_teks: string
  alkohol_radio: string
  alkohol_teks: string
  kopi_radio: string
  kopi_teks: string
  olahraga_radio: string
  olahraga_teks: string
  obat_resep: string
  aspirin_radio: string
  aspirin_teks: string
  anti_sakit_radio: string
  anti_sakit_teks: string
  obat_bebas: string
  alergi_obat: string
  alergi_makanan: string
  keluarga_pendarahan_radio: string
  keluarga_pembekuan_darah_radio: string
  keluarga_pembiusan_radio: string
  keluarga_demam_radio: string
  keluarga_diabetes_radio: string
  keluarga_jantung_radio: string
  keluarga_irama_jantung_radio: string
  keluarga_hipertensi_radio: string
  keluarga_tuberkulosis_radio: string
  keluarga_lainnya_radio: string
  keluarga_teks: string
  pasien_pendarahan_radio: string
  pasien_pembekuan_darah_radio: string
  pasien_maag_radio: string
  pasien_anemia_radio: string
  pasien_jantung_radio: string
  pasien_asthma_radio: string
  pasien_diabetes_radio: string
  pasien_pingsan_radio: string
  pasien_mengorok_radio: string
  pasien_hepatitis_radio: string
  pasien_hipertensi_radio: string
  pasien_lainnya_radio: string
  pasien_kejang_radio: string
  pasien_bawaan_radio: string
  pasien_teks: string
  pasien_transfusi: string
  pasien_transfusi_teks: string
  pasien_diagnosis_hiv: string
  pasien_diagnosis_hiv_teks: string
  pasien_diagnosis_hiv_hasil: string
  pasien_lensa_kontak: string
  pasien_kacamata: string
  pasien_alat_bantu_dengar: string
  pasien_gigi_palsu: string
  pasien_pakai_lainnya: string
  pasien_pakai_lainnya_teks: string
  riwayat_operasi: string
  anestesi_lokal: string
  anestesi_regional: string
  anestesi_umum: string
  sistem_gigi_radio: string
  sistem_mobilisasi_leher_radio: string
  sistem_leher_pendek_radio: string
  sistem_batuk_radio: string
  sistem_sesak_napas_radio: string
  sistem_ispa_radio: string
  sistem_dada_radio: string
  sistem_denyut_jantung_radio: string
  sistem_muntah_radio: string
  sistem_pingsan_radio: string
  sistem_stroke_radio: string
  sistem_kejang_radio: string
  sistem_hamil_radio: string
  sistem_tulang_belakang_radio: string
  sistem_obesitas_radio: string
  sistem_teks: string
  berat_badan: string
  tinggi_badan: string
  tekanan_darah: string
  nadi: string
  suhu: string
  kajian_teks_mallampati: string
  kajian_teks_gigi_palsu: string
  kajian_teks_jantung: string
  kajian_teks_paru: string
  kajian_teks_abdomen: string
  kajian_teks_tulang_belakang: string
  kajian_teks_ekstremitas: string
  kajian_teks_neurologi: string
  kajian_teks_keterangan: string
  laboratorium_hb_ht: string
  laboratorium_pt: string
  laboratorium_glukosa: string
  laboratorium_kehamilan: string
  laboratorium_kalium: string
  laboratorium_ureum: string
  laboratorium_leukosit: string
  laboratorium_trombosit: string
  laboratorium_rontgen: string
  laboratorium_ekg: string
  laboratorium_na_cl: string
  laboratorium_kreatinin: string
  laboratorium_teks: string
  diagnosis_icd_x: string
  asa_1: string
  asa_2: string
  asa_3: string
  asa_4: string
  penyulit_lain_radio: string
  penyulit_lain_teks: string
  catatan_tindak_lanjut: string
  perencanaan_anestesi_sedasi: string
  perencanaan_anestesi_sedasi_teks: string
  perencanaan_anestesi_ga: string
  perencanaan_anestesi_ga_teks: string
  perencanaan_anestesi_lainnya: string
  perencanaan_anestesi_lainnya_teks: string
  perencanaan_khusus_tidak_ada: string
  perencanaan_khusus_hipotensi: string
  perencanaan_khusus_ventilasi: string
  perencanaan_khusus_tci: string
  perencanaan_khusus_lainnya: string
  perencanaan_khusus_lainnya_teks: string
  perencanaan_monitoring_ekg_lead: string
  perencanaan_monitoring_ekg_lead_teks: string
  perencanaan_monitoring_cvp: string
  perencanaan_monitoring_cvp_teks: string
  perencanaan_monitoring_arteri_line: string
  perencanaan_monitoring_arteri_line_teks: string
  perencanaan_monitoring_spo2: string
  perencanaan_monitoring_et_co2: string
  perencanaan_monitoring_nibp: string
  perencanaan_monitoring_bis: string
  perencanaan_monitoring_temp: string
  perencanaan_monitoring_lainnya: string
  perencanaan_monitoring_lainnya_teks: string
  perencanaan_alat_khusus_bronchoscopy: string
  perencanaan_alat_khusus_glidescope: string
  perencanaan_alat_khusus_usg: string
  perencanaan_alat_khusus_lainnya: string
  perencanaan_alat_khusus_lainnya_teks: string
  perencanaan_perawatan_rawat_inap: string
  perencanaan_perawatan_rawat_jalan: string
  perencanaan_perawatan_lainnya: string
  perencanaan_perawatan_lainnya_teks: string
  perencanaan_persiapan_puasa: string
  perencanaan_persiapan_puasa_waktu: string
  perencanaan_persiapan_pre_medikasi: string
  perencanaan_persiapan_pre_medikasi_waktu: string
  perencanaan_persiapan_transportasi_kamar_bedah: string
  perencanaan_persiapan_transportasi_kamar_bedah_waktu: string
  perencanaan_persiapan_rencana_operasi: string
  perencanaan_persiapan_rencana_operasi_waktu: string
  tanda_tangan_pasien: string;
  tanda_tangan_dokter: string;
  id_ttd_dokter: string;
  tidak_ada: string;
  catatan_persiapan_text: string;
}

export interface IUpdatePersetujuanTindakanAnestesi {
  id_dokter_pelaksana: string;
  id_pemberi_informasi: string;
  penerima_informasi: string;
  diagnosis_check: string;
  dasar_diagnosis_check: string;
  dasar_klinis: string;
  dasar_radiologi: string;
  dasar_ekg: string;
  dasar_laboratorium: string;
  tindakan_kedokteran_check: string;
  anestesi_umum_intubasi_check: string;
  anestesi_umum_lma_check: string;
  anestesi_umum_fm_check: string;
  anestesi_umum_tiva_check: string;
  anestesi_regional_spinal_check: string;
  anestesi_regional_epidural_check: string;
  anestesi_regional_perifer_check: string;
  indikasi_tindakan_tujuan_check: string;
  tata_cara_tindakan_check: string;
  tata_cara_tindakan: string;
  risiko_check: string;
  shock_check: string;
  henti_jantung_check: string;
  meninggal_check: string;
  tujuan_check: string;
  tujuan: string;
  komplikasi_check: string;
  komplikasi_umum_1: string;
  komplikasi_umum_2: string;
  komplikasi_umum_3: string;
  komplikasi_umum_4: string;
  komplikasi_umum_5: string;
  komplikasi_umum_6: string;
  komplikasi_umum_7: string;
  komplikasi_umum_8: string;
  komplikasi_umum_9: string;
  komplikasi_umum_10: string;
  komplikasi_regional_1: string;
  komplikasi_regional_2: string;
  komplikasi_regional_3: string;
  komplikasi_regional_4: string;
  komplikasi_regional_5: string;
  komplikasi_regional_6: string;
  komplikasi_regional_7: string;
  komplikasi_regional_8: string;
  komplikasi_regional_9: string;
  komplikasi_regional_10: string;
  komplikasi_regional_11: string;
  komplikasi_regional_12: string;
  prognosis_check: string;
  prognosis: string;
  alternatif_tindakan_check: string;
  alternatif_tindakan: string;
  lain_lain_check: string;
  lain_lain: string;
  id_dokter_pelaksana_ttd: string;
  ttd_dokter_pelaksana: string;
  ttd_penerima_informasi: string;
  pasien_nomor_mr: string
  pasien_nama: string
  pasien_tgl_lahir: string
  pasien_jk: string
  pasien_tindakan_operasi: string
  pernyataan: string
  tindakan_operasi: string;
  nama_saksi_keluarga: string;
  tanda_tangan_saksi_2: string;
  tanda_tangan_hubungan: string;
  tanda_tangan_radio: string
  tanda_tangan_nama: string
  tanda_tangan_tgl_lahir: string
  tanda_tangan_jk: string
  tanda_tangan_telp: string
  tanda_tangan_alamat: string
  pasien_kota: string
  pasien_tanggal: string
  tanda_tangan_pasien: string
  tanda_tangan_saksi: string
  id_saksi: string
  nomor_mr: string
  id_pelayanan: string
  kode_cabang: string
  tipe_pasien: string
  jenis_pelayanan: string
  id_dokter: string
  no_sep: string
}

export interface IUpdateRencanaAsuhanKeperawatan {
  diagnosa_medis: string;
  kamar_id: string;
  perawat_id: string;
  nama_perawat: string;
  // sistem imunitas
  tanggal_si: string;
  diagnosa1_si_check: string;
  diagnosa1_si_1_check: string;
  diagnosa1_si_2_check: string;
  diagnosa1_si_3_check: string;
  diagnosa2_si_check: string;
  diagnosa2_si_1_check: string;
  diagnosa2_si_2_check: string;
  diagnosa2_si_3_check: string;
  diagnosa3_si_check: string;
  diagnosa3_si_1_check: string;
  diagnosa3_si_2_check: string;
  tujuan1_si_check: string;
  tujuan1_si_jam_1: string;
  tujuan1_si_jam_2: string;
  tujuan1_si_1_check: string;
  tujuan1_si_2_check: string;
  tujuan1_si_3_check: string;
  tujuan1_si_3_text: string;
  tujuan2_si_check: string;
  tujuan2_si_jam_1: string;
  tujuan2_si_jam_2: string;
  tujuan2_si_1_check: string;
  tujuan2_si_2_check: string;
  tujuan2_si_3_check: string;
  tujuan2_si_4_check: string;
  tujuan3_si_check: string;
  rencana1_si_1_check: string;
  rencana1_si_2_check: string;
  rencana1_si_3_check: string;
  rencana1_si_4_check: string;
  rencana1_si_5_check: string;
  rencana1_si_6_check: string;
  rencana1_si_7_check: string;
  rencana1_si_8_check: string;
  rencana2_si_1_check: string;
  rencana2_si_1_text: string;
  rencana2_si_2_check: string;
  rencana2_si_2_text: string;
  rencana2_si_3_check: string;
  rencana2_si_3_text: string;
  //persepsi - sensori
  tanggal_ps: string;
  diagnosa1_ps_check: string;
  diagnosa1_ps_1_check: string;
  diagnosa1_ps_1_text: string;
  diagnosa1_ps_2_check: string;
  diagnosa1_ps_2_text: string;
  diagnosa1_ps_3_check: string;
  diagnosa1_ps_3_text: string;
  diagnosa1_ps_4_check: string;
  diagnosa1_ps_5_check: string;
  diagnosa1_ps_6_check: string;
  tujuan1_ps_check: string;
  tujuan1_ps_jam_1: string;
  tujuan1_ps_jam_2: string;
  tujuan1_ps_1_check: string;
  tujuan1_ps_2_check: string;
  tujuan1_ps_3_check: string;
  tujuan1_ps_4_check: string;
  rencana1_ps_1_check: string;
  rencana1_ps_2_check: string;
  rencana1_ps_3_check: string;
  rencana1_ps_4_check: string;
  rencana1_ps_5_check: string;
  rencana1_ps_6_check: string;
  rencana1_ps_7_check: string;
  rencana2_ps_1_check: string;
  rencana2_ps_1_text: string;
  rencana2_ps_2_check: string;
  rencana2_ps_2_text: string;
  rencana2_ps_3_check: string;
  rencana2_ps_3_text: string;
  // nutrisi cairan dan eliminasi
  tanggal_nc: string;
  diagnosa1_nc_check: string;
  diagnosa1_nc_1_check: string;
  diagnosa1_nc_2_check: string;
  diagnosa1_nc_3_check: string;
  diagnosa2_nc_check: string;
  diagnosa2_nc_1_check: string;
  diagnosa3_nc_check: string;
  diagnosa3_nc_1_check: string;
  diagnosa3_nc_2_check: string;
  diagnosa3_nc_3_check: string;
  diagnosa3_nc_4_check: string;
  diagnosa3_nc_5_check: string;
  diagnosa3_nc_5_text: string;
  diagnosa4_nc_check: string;
  diagnosa4_nc_1_check: string;
  diagnosa5_nc_check: string;
  diagnosa5_nc_1_check: string;
  diagnosa5_nc_2_check: string;
  tujuan1_nc_check: string;
  tujuan1_nc_jam_1: string;
  tujuan1_nc_jam_2: string;
  tujuan1_nc_1_check: string;
  tujuan1_nc_2_check: string;
  tujuan1_nc_3_check: string;
  tujuan1_nc_4_check: string;
  tujuan1_nc_5_check: string;
  tujuan1_nc_6_check: string;
  tujuan1_nc_6_text: string;
  tujuan2_nc_check: string;
  tujuan2_nc_jam_1: string;
  tujuan2_nc_jam_2: string;
  tujuan2_nc_1_check: string;
  tujuan2_nc_2_check: string;
  tujuan2_nc_3_check: string;
  tujuan2_nc_4_check: string;
  tujuan3_nc_check: string;
  tujuan3_nc_jam_1: string;
  tujuan3_nc_jam_2: string;
  tujuan3_nc_1_check: string;
  tujuan3_nc_2_check: string;
  tujuan3_nc_3_check: string;
  tujuan4_nc_check: string;
  rencana1_nc_1_check: string;
  rencana1_nc_2_check: string;
  rencana1_nc_3_check: string;
  rencana1_nc_4_check: string;
  rencana1_nc_5_check: string;
  rencana1_nc_6_check: string;
  rencana1_nc_7_check: string;
  rencana1_nc_8_check: string;
  rencana1_nc_9_check: string;
  rencana1_nc_10_check: string;
  rencana1_nc_11_check: string;
  rencana1_nc_12_check: string;
  rencana1_nc_12_text: string;
  rencana2_nc_1_check: string;
  rencana2_nc_2_check: string;
  rencana2_nc_3_check: string;
  rencana2_nc_3_text: string;
  //kebersihan diri dan aktivitas
  tanggal_kd: string;
  diagnosa1_kd_check: string;
  diagnosa1_kd_1_check: string;
  diagnosa1_kd_2_check: string;
  diagnosa1_kd_3_check: string;
  diagnosa1_kd_4_check: string;
  diagnosa2_kd_check: string;
  diagnosa2_kd_text: string;
  tujuan1_kd_check: string;
  tujuan1_kd_jam_1: string;
  tujuan1_kd_jam_2: string;
  tujuan1_kd_1_check: string;
  tujuan1_kd_2_check: string;
  tujuan2_kd_check: string;
  tujuan2_kd_jam_1: string;
  tujuan2_kd_jam_2: string;
  tujuan2_kd_1_check: string;
  tujuan2_kd_1_text: string;
  rencana1_kd_1_check: string;
  rencana1_kd_2_check: string;
  rencana1_kd_3_check: string;
  rencana1_kd_4_check: string;
  rencana1_kd_5_check: string;
  rencana1_kd_6_check: string;
  rencana1_kd_7_check: string;
  rencana1_kd_7_text: string;
  rencana2_kd_1_check: string;
  rencana2_kd_1_text: string;
  // istirahat dan tidur
  tanggal_it: string;
  diagnosa1_it_check: string;
  diagnosa1_it_1_check: string;
  diagnosa1_it_2_check: string;
  diagnosa2_it_check: string;
  diagnosa2_it_1_check: string;
  diagnosa2_it_2_check: string;
  diagnosa2_it_3_check: string;
  diagnosa3_it_check: string;
  diagnosa3_it_text: string;
  tujuan1_it_check: string;
  tujuan1_it_jam_1: string;
  tujuan1_it_jam_2: string;
  tujuan1_it_1_check: string;
  tujuan1_it_2_check: string;
  tujuan1_it_3_check: string;
  tujuan1_it_4_check: string;
  tujuan2_it_check: string;
  tujuan2_it_jam_1: string;
  tujuan2_it_jam_2: string;
  tujuan2_it_1_check: string;
  tujuan2_it_2_check: string;
  tujuan2_it_2_text: string;
  rencana1_it_1_check: string;
  rencana1_it_2_check: string;
  rencana1_it_3_check: string;
  rencana1_it_4_check: string;
  rencana1_it_5_check: string;
  rencana1_it_6_check: string;
  rencana1_it_7_check: string;
  rencana1_it_8_check: string;
  rencana1_it_9_check: string;
  rencana1_it_10_check: string;
  rencana1_it_10_text: string;
  rencana2_it_1_check: string;
  rencana2_it_1_text: string;
  rencana2_it_2_check: string;
  rencana2_it_2_text: string;
  // psikososial dan spiritual
  tanggal_psi: string;
  diagnosa1_psi_check: string;
  diagnosa1_psi_1_check: string;
  diagnosa1_psi_2_check: string;
  diagnosa1_psi_3_check: string;
  diagnosa1_psi_4_check: string;
  diagnosa1_psi_5_check: string;
  diagnosa2_psi_check: string;
  diagnosa2_psi_1_check: string;
  diagnosa2_psi_2_check: string;
  diagnosa2_psi_3_check: string;
  diagnosa3_psi_check: string;
  diagnosa3_psi_1_check: string;
  diagnosa3_psi_2_check: string;
  diagnosa3_psi_3_check: string;
  tujuan1_psi_check: string;
  tujuan1_psi_jam_1: string;
  tujuan1_psi_jam_2: string;
  tujuan1_psi_1_check: string;
  tujuan1_psi_2_check: string;
  tujuan1_psi_3_check: string;
  tujuan1_psi_4_check: string;
  tujuan2_psi_check: string;
  tujuan2_psi_jam_1: string;
  tujuan2_psi_jam_2: string;
  tujuan2_psi_1_check: string;
  tujuan2_psi_2_check: string;
  tujuan3_psi_check: string;
  tujuan3_psi_jam_1: string;
  tujuan3_psi_jam_2: string;
  tujuan3_psi_1_check: string;
  tujuan3_psi_2_check: string;
  tujuan3_psi_3_check: string;
  rencana1_psi_1_check: string;
  rencana1_psi_2_check: string;
  rencana1_psi_3_check: string;
  rencana1_psi_4_check: string;
  rencana1_psi_5_check: string;
  rencana1_psi_6_check: string;
  rencana1_psi_7_check: string;
  rencana1_psi_8_check: string;
  rencana1_psi_9_check: string;
  rencana1_psi_10_check: string;
  rencana1_psi_11_check: string;
  rencana2_psi_1_check: string;
  rencana2_psi_2_check: string;
  rencana2_psi_2_text: string;
  rencana2_psi_3_check: string;
  rencana2_psi_3_text: string;
  // persepsi - sensori penglihatan
  tanggal_ps1: string;
  diagnosa1_ps1_check: string;
  diagnosa1_ps1_1_check: string;
  diagnosa1_ps1_1_text: string;
  diagnosa1_ps1_2_check: string;
  diagnosa1_ps1_2_text: string;
  diagnosa1_ps1_3_check: string;
  diagnosa1_ps1_3_text: string;
  diagnosa1_ps1_4_check: string;
  diagnosa1_ps1_5_check: string;
  tujuan1_ps1_check: string;
  tujuan1_ps1_1_check: string;
  tujuan1_ps1_2_check: string;
  rencana1_ps1_1_check: string;
  rencana1_ps1_2_check: string;
  rencana1_ps1_3_check: string;
  rencana1_ps1_4_check: string;
  rencana1_ps1_5_check: string;
  rencana2_ps1_1_check: string;
  rencana2_ps1_2_check: string;
  rencana2_ps1_2_text: string;
  // sistem imunitas
  tanggal_si1: string;
  diagnosa1_si1_check: string;
  diagnosa1_si1_1_check: string;
  diagnosa1_si1_2_check: string;
  diagnosa1_si1_3_check: string;
  diagnosa1_si1_4_check: string;
  diagnosa1_si1_5_check: string;
  tujuan1_si1_check: string;
  tujuan1_si1_jam_1: string;
  tujuan1_si1_jam_2: string;
  tujuan1_si1_1_check: string;
  tujuan1_si1_2_check: string;
  tujuan1_si1_3_check: string;
  rencana1_si1_1_check: string;
  rencana1_si1_2_check: string;
  rencana1_si1_3_check: string;
  rencana1_si1_4_check: string;
  rencana1_si1_5_check: string;
  rencana1_si1_6_check: string;
  rencana1_si1_7_check: string;
  rencana1_si1_8_check: string;
  rencana2_si1_1_check: string;
  rencana2_si1_1_text: string;
  rencana2_si1_2_check: string;
  rencana2_si1_2_text: string;
  rencana2_si1_3_check: string;
  rencana2_si1_3_text: string;
}

export interface IUpdateSuratPerintahRawatInap {
  id_dokter_rawat_inap: string;
  tanggal_tanda_tangan: string;
  indikasi_opname: string;
  anjuran_opname: string;
  preventif_check: string;
  paliatif_check: string;
  kuratif_check: string;
  rehabilitatif_check: string;
  diagnosa: string;
  lama_opname: string;
  lama_satuan: string;
  ttd_dokter: string;
}

export interface IUpdatePengkajianAwalGizi {
  tanggal: string;
  diagnosa_masuk: string;
  diet_awal: string;
  bb_anak: string;
  tb_anak: string;
  bb_0_12_anak: string;
  bb_1_13_anak: string;
  bb_ideal_anak: string;
  z_score: string;
  bb_dewasa: string;
  tb_dewasa: string;
  bb_ideal_dewasa: string;
  status_gizi: string;
  gangguan_gastro: string;
  gangguan_gastro_ada: string;
  perubahan_asupan: string;
  perubahan_asupan_ada: string;
  faktor_resiko: string;
  resiko_diabetes: string;
  resiko_hipertensi: string;
  resiko_luka_bakar: string;
  resiko_kanker: string;
  resiko_dislipidemia: string;
  resiko_gangguan_ginjal: string;
  resiko_gangguan_lain: string;
  resiko_gangguan_lain_teks: string;
  resiko_gangguan_jantung: string;
  resiko_stroke: string;
  resiko_gastritis: string;
  resiko_thyphoid: string;
  resiko_lainnya: string;
  resiko_lainnya_teks: string;
  imt: string;
  keterangan_gizi: string;
  diagnosa_gizi: string;
  intervensi: string;
  monitoring: string;
  evaluasi: string;
  nama_petugas_gizi: string;
  id_petugas_gizi: string;
  ttd_petugas_gizi: string;
}

export interface IUpdateMonitoringSkalaNyeri {
  id: string;
  waktu_monitor: string;
  tekanan_darah: string;
  nadi: string;
  rr: string;
  lokasi_nyeri: string;
  tindakan: string;
  id_perawat: string;
  ttd_perawat: string;
  temperatur: string;
  total_skor: string;
  skala_nyeri: string;
}

export interface IUpdatePemberianInformasiResikoPasienJatuh {
  id_pemberi_informasi: string;
  penerima_informasi: string;
  nama_wali: string;
  faktor_usia_check: string;
  faktor_riwayat_jatuh_check: string;
  faktor_penyakit_check: string;
  faktor_penggunaan_alat_check: string;
  faktor_terpasang_infus_check: string;
  faktor_kondisi_mental_check: string;
  faktor_mobilisasi_check: string;
  faktor_mobilisasi_text: string;
  faktor_post_operasi_check: string;
  faktor_post_operasi_text: string;
  faktor_respon_obat_check : string;
  respon_obat_sedatif: string;
  respon_obat_hipnotik: string;
  respon_obat_antidepresan: string;
  respon_obat_laxatives: string;
  respon_obat_diuretika: string;
  respon_obat_narkotika: string;
  faktor_riwayat_check: string;
  riwayat_kejang: string;
  riwayat_vertigo: string;
  riwayat_depresi: string;
  riwayat_pingsan: string;
  riwayat_pusing: string;
  riwayat_delirium: string;
  riwayat_disorientasi: string;
  faktor_lain_check: string;
  faktor_lain_text: string;
  tingkatan_check: string;
  tingkatan_rendah: string;
  tingkatan_sedang: string;
  tingkatan_tinggi: string;
  tindakan_rem_tempat_tidur_check: string;
  tindakan_kebutuhan_pasien_check: string;
  tindakan_tempatkan_meja_check: string;
  tindakan_pasang_palang_check: string;
  tindakan_pasang_penanda_check: string;
  tindakan_libatkan_keluarga_check: string;
  tindakan_cepat_menanggapi_check: string;
  tujuan_pasien_aman_check: string;
  akibat_timbulnya_cedera_check: string;
  lainnya_check: string;
  lainnya_text: string;
  id_ttd_pemberi_informasi: string;
  ttd_pemberi_informasi: string;
  id_ttd_penerima_informasi: string;
  ttd_penerima_informasi: string;
}

export interface IUpdateSurveilansInfeksiHais {
  ruangan_hais: string;
  tanggal_berobat: string;
  diagnosa_masuk: string;
  asal_masuk: string;
  vena_sentral_check: string;
  vena_perifer_check: string;
  lokasi_vs: string;
  mulai_vs: string;
  selesai_vs: string;
  total_hari_vs: string;
  tanggal_infeksi_vs: string;
  catatan_vs: string;
  lokasi_vp: string;
  mulai_vp: string;
  selesai_vp: string;
  total_hari_vp: string;
  tanggal_infeksi_vp: string;
  catatan_vp: string;
  tindakan_alkes_lain: string;
  lokasi_lain: string;
  mulai_lain: string;
  selesai_lain: string;
  total_hari_lain: string;
  tanggal_infeksi_lain: string;
  catatan_lain: string;
  hbs_ag: string;
  anti_hcv: string;
  anti_hiv: string;
  faktor_penyakit_lain: string;
  lab_leukocyt: string;
  lab_led: string;
  lab_lain: string;
  hasil_radiologi: string;
  merokok: string;
  steroid_jangka_panjang: string;
  mandi_sebelum_operasi: string;
  operasi_karena_trauma: string;
  obat_pengencer_darah: string;
  memakai_make_up: string;
  gula_darah: string
  suhu_pasien: string;
  infeksi_mata_check: string;
  infeksi_tht_check: string;
  infeksi_mulut_check: string;
  infeksi_paru_check: string;
  infeksi_kulit_check: string;
  infeksi_gi_check: string;
  infeksi_lainnya_check: string;
  infeksi_lainnya_text: string;
  penyakit_dm_check: string;
  penyakit_hipertensi_check: string;
  penyakit_ggk_check: string;
  penyakit_sepsis_check: string;
  riwayat_pasien_sekarang: string;
  jenis_operasi: string;
  asa_score: string;
  jenis_anestesi: string;
  operator_anestesi: string;
  kelembapan_udara: string;
  suhu_ruangan: string;
  komplikasi_saat_operasi: string;
  profilaksis: string;
  obat_profilaksis: string;
  antibiotik_tambahan: string;
  obat_antibiotik: string;
  dosis_antibiotik: string;
  jam_diberikan_antibiotik: string;
  probe_laser: string;
  tubing_vitrectomy: string;
  chlorhexidine_check: string;
  povidone_iodine_check: string;
  alkohol_70_check: string;
  jahitan: string;
  indikator_instrumen: string;
  sterilisasi_cssd: string;
  inisial_dr: string;
  asisten_op: string;
  urutan_op: string;
  implant: string;
  lama_op: string;
  ruang_operasi: string;
  klasifikasi_luka: string;
  prosedur_op: string;
  kualifikasi_dokter_bedah: string;
  jumlah_staf: string;
  diagnosa_akhir: string;
  tanggal_pasien_keluar: string;
  cara_pasien_keluar: string;
  nama_pindah_faskes: string;
  id_perawat: string;
  ttd_perawat: string;
  id_perawat_ipcn: string;
  ttd_perawat_ipcn: string;
}

