import { isValidFile } from "../../helpers/app.helper";
import { IUpdateEdukasiTerintegrasi } from "./integrated-education.request";

export class EdukasiTerintegrasi {
  static createFromJson(json: IUpdateEdukasiTerintegrasi) {
    const assessments = {
      1: json.asesmen && Array.isArray(json.asesmen) && json.asesmen.includes('1') ? 1 : 0,
      2: json.asesmen && Array.isArray(json.asesmen) && json.asesmen.includes('2') ? 1 : 0,
      3: json.asesmen && Array.isArray(json.asesmen) && json.asesmen.includes('3') ? 1 : 0,
      4: json.asesmen && Array.isArray(json.asesmen) && json.asesmen.includes('4') ? 1 : 0,
      5: json.asesmen && Array.isArray(json.asesmen) && json.asesmen.includes('5') ? 1 : 0,
      6: json.asesmen && Array.isArray(json.asesmen) && json.asesmen.includes('6') ? 1 : 0,
      7: json.asesmen && Array.isArray(json.asesmen) && json.asesmen.includes('7') ? 1 : 0,
      8: json.asesmen && Array.isArray(json.asesmen) && json.asesmen.includes('8') ? 1 : 0,
      9: json.asesmen && Array.isArray(json.asesmen) && json.asesmen.includes('9') ? 1 : 0,
      10: json.asesmen && Array.isArray(json.asesmen) && json.asesmen.includes('10') ? 1 : 0,
      11: json.asesmen && Array.isArray(json.asesmen) && json.asesmen.includes('11') ? 1 : 0,
    }
    return {
      TTD_Penerima_Edukasi_DPJP: json.ttd_penerima_edukasi_dpjp && json.ttd_penerima_edukasi_dpjp !== '' && isValidFile(json.ttd_penerima_edukasi_dpjp) ? global.storage.cleanUrl(json.ttd_penerima_edukasi_dpjp) : '',
      TTD_Penerima_Edukasi_Gizi: json.ttd_penerima_edukasi_gizi && json.ttd_penerima_edukasi_gizi !== '' && isValidFile(json.ttd_penerima_edukasi_gizi) ? global.storage.cleanUrl(json.ttd_penerima_edukasi_gizi) : '',
      TTD_Penerima_Edukasi_Manajemen_Nyeri: json.ttd_penerima_edukasi_manajemen_nyeri && json.ttd_penerima_edukasi_manajemen_nyeri !== '' && isValidFile(json.ttd_penerima_edukasi_manajemen_nyeri) ? global.storage.cleanUrl(json.ttd_penerima_edukasi_manajemen_nyeri) : '',
      TTD_Penerima_Edukasi_Post_Operasi: json.ttd_penerima_edukasi_post_op && json.ttd_penerima_edukasi_post_op !== '' && isValidFile(json.ttd_penerima_edukasi_post_op) ? global.storage.cleanUrl(json.ttd_penerima_edukasi_post_op) : '',
      TTD_Penerima_Edukasi_Keperawatan: json.ttd_penerima_edukasi_keperawatan && json.ttd_penerima_edukasi_keperawatan !== '' && isValidFile(json.ttd_penerima_edukasi_keperawatan) ? global.storage.cleanUrl(json.ttd_penerima_edukasi_keperawatan) : '',
      TTD_Penerima_Edukasi_Farmasi: json.ttd_penerima_edukasi_farmasi && json.ttd_penerima_edukasi_farmasi !== '' && isValidFile(json.ttd_penerima_edukasi_farmasi) ? global.storage.cleanUrl(json.ttd_penerima_edukasi_farmasi) : '',
      TTD_Penerima_Edukasi_Dokter: json.ttd_penerima_edukasi_dokter && json.ttd_penerima_edukasi_dokter !== '' && isValidFile(json.ttd_penerima_edukasi_dokter) ? global.storage.cleanUrl(json.ttd_penerima_edukasi_dokter) : '',
      TTD_Penerima_Edukasi_Rohaniawan: json.ttd_penerima_edukasi_rohaniawan && json.ttd_penerima_edukasi_rohaniawan !== '' && isValidFile(json.ttd_penerima_edukasi_rohaniawan) ? global.storage.cleanUrl(json.ttd_penerima_edukasi_rohaniawan) : '',
      TTD_Penerima_Edukasi_Mencuci_Tangan: json.ttd_penerima_edukasi_mencuci_tangan && json.ttd_penerima_edukasi_mencuci_tangan !== '' && isValidFile(json.ttd_penerima_edukasi_mencuci_tangan) ? global.storage.cleanUrl(json.ttd_penerima_edukasi_mencuci_tangan) : '',
      TTD_Penerima_Edukasi_Penggunaan_Peralatan: json.ttd_penerima_edukasi_penggunaan_peralatan && json.ttd_penerima_edukasi_penggunaan_peralatan !== '' && isValidFile(json.ttd_penerima_edukasi_penggunaan_peralatan) ? global.storage.cleanUrl(json.ttd_penerima_edukasi_penggunaan_peralatan) : '',
      TTD_Penerima_Edukasi_Hak_Kewajiban: json.ttd_penerima_edukasi_rohaniawan && json.ttd_penerima_edukasi_rohaniawan !== '' && isValidFile(json.ttd_penerima_edukasi_rohaniawan) ? global.storage.cleanUrl(json.ttd_penerima_edukasi_rohaniawan) : '',
      TTD_Penerima_Edukasi_Informasi_Lain: json.ttd_penerima_edukasi_informasi_lain && json.ttd_penerima_edukasi_informasi_lain !== '' && isValidFile(json.ttd_penerima_edukasi_informasi_lain) ? global.storage.cleanUrl(json.ttd_penerima_edukasi_informasi_lain) : '',

      TTD_Edukator_DPJP: json.ttd_edukator_dpjp && json.ttd_edukator_dpjp !== '' && isValidFile(json.ttd_edukator_dpjp) ? global.storage.cleanUrl(json.ttd_edukator_dpjp) : '',
      TTD_Edukator_Gizi: json.ttd_edukator_gizi && json.ttd_edukator_gizi !== '' && isValidFile(json.ttd_edukator_gizi) ? global.storage.cleanUrl(json.ttd_edukator_gizi) : '',
      TTD_Edukator_Manajemen_Nyeri: json.ttd_edukator_manajemen_nyeri && json.ttd_edukator_manajemen_nyeri !== '' && isValidFile(json.ttd_edukator_manajemen_nyeri) ? global.storage.cleanUrl(json.ttd_edukator_manajemen_nyeri) : '',
      TTD_Edukator_Post_Operasi: json.ttd_edukator_post_op && json.ttd_edukator_post_op !== '' && isValidFile(json.ttd_edukator_post_op) ? global.storage.cleanUrl(json.ttd_edukator_post_op) : '',
      TTD_Edukator_Keperawatan: json.ttd_edukator_keperawatan && json.ttd_edukator_keperawatan !== '' && isValidFile(json.ttd_edukator_keperawatan) ? global.storage.cleanUrl(json.ttd_edukator_keperawatan) : '',
      TTD_Edukator_Farmasi: json.ttd_edukator_farmasi && json.ttd_edukator_farmasi !== '' && isValidFile(json.ttd_edukator_farmasi) ? global.storage.cleanUrl(json.ttd_edukator_farmasi) : '',
      TTD_Edukator_Dokter: json.ttd_edukator_dokter && json.ttd_edukator_dokter !== '' && isValidFile(json.ttd_edukator_dokter) ? global.storage.cleanUrl(json.ttd_edukator_dokter) : '',
      TTD_Edukator_Rohaniawan: json.ttd_edukator_rohaniawan && json.ttd_edukator_rohaniawan !== '' && isValidFile(json.ttd_edukator_rohaniawan) ? global.storage.cleanUrl(json.ttd_edukator_rohaniawan) : '',
      TTD_Edukator_Mencuci_Tangan: json.ttd_edukator_mencuci_tangan && json.ttd_edukator_mencuci_tangan !== '' && isValidFile(json.ttd_edukator_mencuci_tangan) ? global.storage.cleanUrl(json.ttd_edukator_mencuci_tangan) : '',
      TTD_Edukator_Penggunaan_Peralatan: json.ttd_edukator_penggunaan_peralatan && json.ttd_edukator_penggunaan_peralatan !== '' && isValidFile(json.ttd_edukator_penggunaan_peralatan) ? global.storage.cleanUrl(json.ttd_edukator_penggunaan_peralatan) : '',
      TTD_Edukator_Hak_Kewajiban: json.ttd_edukator_hak_kewajiban && json.ttd_edukator_hak_kewajiban !== '' && isValidFile(json.ttd_edukator_hak_kewajiban) ? global.storage.cleanUrl(json.ttd_edukator_hak_kewajiban) : '',
      TTD_Edukator_Informasi_Lain: json.ttd_edukator_informasi_lain && json.ttd_edukator_informasi_lain !== '' && isValidFile(json.ttd_edukator_informasi_lain) ? global.storage.cleanUrl(json.ttd_edukator_informasi_lain) : '',

      ID_Edukator_DPJP: json.id_edukator_dpjp ?? '',
      // Nama_Edukator_DPJP
      ID_Edukator_Gizi: json.id_edukator_gizi ?? '',
      // Nama_Edukator_Gizi
      ID_Edukator_Manajemen_Nyeri: json.id_edukator_manajemen_nyeri ?? '',
      // Nama_Edukator_Manajemen_Nyeri
      ID_Edukator_Post_Operasi: json.id_edukator_post_op ?? '',
      // Nama_Edukator_Post_Operasi
      ID_Edukator_Keperawatan: json.id_edukator_keperawatan ?? '',
      // Nama_Edukator_Keperawatan
      ID_Edukator_Farmasi: json.id_edukator_farmasi ?? '',
      // Nama_Edukator_Farmasi
      ID_Edukator_Dokter: json.id_edukator_dokter ?? '',
      // Nama_Edukator_Dokter
      ID_Edukator_Rohaniawan: json.id_edukator_rohaniawan ?? '',
      // Nama_Edukator_Rohaniawan
      ID_Edukator_Mencuci_Tangan: json.id_edukator_mencuci_tangan ?? '',
      // Nama_Edukator_Mencuci_Tangan
      ID_Edukator_Penggunaan_Peralatan: json.id_edukator_penggunaan_peralatan ?? '',
      // Nama_Edukator_Penggunaan_Peralatan
      ID_Edukator_Hak_Kewajiban: json.id_edukator_hak_kewajiban ?? '',
      // Nama_Edukator_Hak_Kewajiban
      ID_Edukator_Informasi_Lain: json.id_edukator_informasi_lain ?? '',
      // Nama_Edukator_Informasi_Lain

      DPJP: {
        ID_DPJP: json.dpjp ?? '',
        Metode_Pembelajaran: {
          Diskusi: json.dpjp_diskusi && json.dpjp_diskusi === '1' ? 1 : 0,
          Demonstrasi: json.dpjp_demonstrasi && json.dpjp_demonstrasi === '1' ? 1 : 0,
          Ceramah: json.dpjp_ceramah && json.dpjp_ceramah === '1' ? 1 : 0,
          Solusi: json.dpjp_solusi && json.dpjp_solusi === '1' ? 1 : 0,
          Observatori: json.dpjp_observatori && json.dpjp_observatori === '1' ? 1 : 0,
          Lain: json.dpjp_metode_pembelajaran_lain && json.dpjp_metode_pembelajaran_lain === '1' ? 1 : 0,
          Lain_Teks: json.dpjp_metode_pembelajaran_lain_teks ?? '',
        },
        Evaluasi_Pasien: {
          Mampu_Memahami: json.dpjp_mampu_memahami && json.dpjp_mampu_memahami === '1' ? 1 : 0,
          Mampu_Mengerti: json.dpjp_mampu_mengerti && json.dpjp_mampu_mengerti === '1' ? 1 : 0,
          Lain: json.dpjp_evaluasi_pasien_lain && json.dpjp_evaluasi_pasien_lain === '1' ? 1 : 0,
          Lain_Teks: json.dpjp_evaluasi_pasien_lain_teks ?? '',
        },
        Waktu_Edukasi: json.dpjp_waktu_edukasi ?? '',
        Durasi: json.dpjp_durasi ?? '',
        Penerima_Edukasi: {
          Pasien: json.dpjp_pasien && json.dpjp_pasien === '1' ? 1 : 0,
          Pasangan: json.dpjp_pasangan && json.dpjp_pasangan === '1' ? 1 : 0,
          Orang_Tua: json.dpjp_orang_tua && json.dpjp_orang_tua === '1' ? 1 : 0,
          Saudara_Kandung: json.dpjp_saudara_kandung && json.dpjp_saudara_kandung === '1' ? 1 : 0,
          Lain: json.dpjp_penerima_edukasi_lain && json.dpjp_penerima_edukasi_lain === '1' ? 1 : 0,
          Lain_Teks: json.dpjp_penerima_edukasi_lain_teks ?? '',
        },
      },
      Gizi: {
        Metode_Pembelajaran: {
          Diskusi: json.gizi_diskusi && json.gizi_diskusi === '1' ? 1 : 0,
          Demonstrasi: json.gizi_demonstrasi && json.gizi_demonstrasi === '1' ? 1 : 0,
          Ceramah: json.gizi_ceramah && json.gizi_ceramah === '1' ? 1 : 0,
          Solusi: json.gizi_solusi && json.gizi_solusi === '1' ? 1 : 0,
          Observatori: json.gizi_observatori && json.gizi_observatori === '1' ? 1 : 0,
          Lain: json.gizi_metode_pembelajaran_lain && json.gizi_metode_pembelajaran_lain === '1' ? 1 : 0,
          Lain_Teks: json.gizi_metode_pembelajaran_lain_teks ?? '',
        },
        Evaluasi_Pasien: {
          Mampu_Memahami: json.gizi_mampu_memahami && json.gizi_mampu_memahami === '1' ? 1 : 0,
          Mampu_Mengerti: json.gizi_mampu_mengerti && json.gizi_mampu_mengerti === '1' ? 1 : 0,
          Lain: json.gizi_evaluasi_pasien_lain && json.gizi_evaluasi_pasien_lain === '1' ? 1 : 0,
          Lain_Teks: json.gizi_evaluasi_pasien_lain_teks ?? '',
        },
        Waktu_Edukasi: json.gizi_waktu_edukasi ?? '',
        Durasi: json.gizi_durasi ?? '',
        Penerima_Edukasi: {
          Pasien: json.gizi_pasien && json.gizi_pasien === '1' ? 1 : 0,
          Pasangan: json.gizi_pasangan && json.gizi_pasangan === '1' ? 1 : 0,
          Orang_Tua: json.gizi_orang_tua && json.gizi_orang_tua === '1' ? 1 : 0,
          Saudara_Kandung: json.gizi_saudara_kandung && json.gizi_saudara_kandung === '1' ? 1 : 0,
          Lain: json.gizi_penerima_edukasi_lain && json.gizi_penerima_edukasi_lain === '1' ? 1 : 0,
          Lain_Teks: json.gizi_evaluasi_pasien_lain_teks ?? '',
        },
      },
      Manajemen_Nyeri: {
        Metode_Pembelajaran: {
          Diskusi: json.manajemen_nyeri_diskusi && json.manajemen_nyeri_diskusi === '1' ? 1 : 0,
          Demonstrasi: json.manajemen_nyeri_demonstrasi && json.manajemen_nyeri_demonstrasi === '1' ? 1 : 0,
          Ceramah: json.manajemen_nyeri_ceramah && json.manajemen_nyeri_ceramah === '1' ? 1 : 0,
          Solusi: json.manajemen_nyeri_solusi && json.manajemen_nyeri_solusi === '1' ? 1 : 0,
          Observatori: json.manajemen_nyeri_observatori && json.manajemen_nyeri_observatori === '1' ? 1 : 0,
          Lain: json.manajemen_nyeri_metode_pembelajaran_lain && json.manajemen_nyeri_metode_pembelajaran_lain === '1' ? 1 : 0,
          Lain_Teks: json.manajemen_nyeri_metode_pembelajaran_lain_teks ?? '',
        },
        Evaluasi_Pasien: {
          Mampu_Memahami: json.manajemen_nyeri_mampu_memahami && json.manajemen_nyeri_mampu_memahami === '1' ? 1 : 0,
          Mampu_Mengerti: json.manajemen_nyeri_mampu_mengerti && json.manajemen_nyeri_mampu_mengerti === '1' ? 1 : 0,
          Lain: json.manajemen_nyeri_evaluasi_pasien_lain && json.manajemen_nyeri_evaluasi_pasien_lain === '1' ? 1 : 0,
          Lain_Teks: json.manajemen_nyeri_evaluasi_pasien_lain_teks ?? '',
        },
        Waktu_Edukasi: json.manajemen_nyeri_waktu_edukasi ?? '',
        Durasi: json.manajemen_nyeri_durasi ?? '',
        Penerima_Edukasi: {
          Pasien: json.manajemen_nyeri_pasien && json.manajemen_nyeri_pasien === '1' ? 1 : 0,
          Pasangan: json.manajemen_nyeri_pasangan && json.manajemen_nyeri_pasangan === '1' ? 1 : 0,
          Orang_Tua: json.manajemen_nyeri_orang_tua && json.manajemen_nyeri_orang_tua === '1' ? 1 : 0,
          Saudara_Kandung: json.manajemen_nyeri_saudara_kandung && json.manajemen_nyeri_saudara_kandung === '1' ? 1 : 0,
          Lain: json.manajemen_nyeri_penerima_edukasi_lain && json.manajemen_nyeri_penerima_edukasi_lain === '1' ? 1 : 0,
          Lain_Teks: json.manajemen_nyeri_evaluasi_pasien_lain_teks ?? '',
        },
      },
      Post_Operasi: {
        Metode_Pembelajaran: {
          Diskusi: json.post_op_diskusi && json.post_op_diskusi === '1' ? 1 : 0,
          Demonstrasi: json.post_op_demonstrasi && json.post_op_demonstrasi === '1' ? 1 : 0,
          Ceramah: json.post_op_ceramah && json.post_op_ceramah === '1' ? 1 : 0,
          Solusi: json.post_op_solusi && json.post_op_solusi === '1' ? 1 : 0,
          Observatori: json.post_op_observatori && json.post_op_observatori === '1' ? 1 : 0,
          Lain: json.post_op_metode_pembelajaran_lain && json.post_op_metode_pembelajaran_lain === '1' ? 1 : 0,
          Lain_Teks: json.post_op_metode_pembelajaran_lain_teks ?? '',
        },
        Evaluasi_Pasien: {
          Mampu_Memahami: json.post_op_mampu_memahami && json.post_op_mampu_memahami === '1' ? 1 : 0,
          Mampu_Mengerti: json.post_op_mampu_mengerti && json.post_op_mampu_mengerti === '1' ? 1 : 0,
          Lain: json.post_op_evaluasi_pasien_lain && json.post_op_evaluasi_pasien_lain === '1' ? 1 : 0,
          Lain_Teks: json.post_op_evaluasi_pasien_lain_teks ?? '',
        },
        Waktu_Edukasi: json.post_op_waktu_edukasi ?? '',
        Durasi: json.post_op_durasi ?? '',
        Penerima_Edukasi: {
          Pasien: json.post_op_pasien && json.post_op_pasien === '1' ? 1 : 0,
          Pasangan: json.post_op_pasangan && json.post_op_pasangan === '1' ? 1 : 0,
          Orang_Tua: json.post_op_orang_tua && json.post_op_orang_tua === '1' ? 1 : 0,
          Saudara_Kandung: json.post_op_saudara_kandung && json.post_op_saudara_kandung === '1' ? 1 : 0,
          Lain: json.post_op_penerima_edukasi_lain && json.post_op_penerima_edukasi_lain === '1' ? 1 : 0,
          Lain_Teks: json.post_op_evaluasi_pasien_lain_teks ?? '',
        },
      },
      Keperawatan: {
        Metode_Pembelajaran: {
          Diskusi: json.keperawatan_diskusi && json.keperawatan_diskusi === '1' ? 1 : 0,
          Demonstrasi: json.keperawatan_demonstrasi && json.keperawatan_demonstrasi === '1' ? 1 : 0,
          Ceramah: json.keperawatan_ceramah && json.keperawatan_ceramah === '1' ? 1 : 0,
          Solusi: json.keperawatan_solusi && json.keperawatan_solusi === '1' ? 1 : 0,
          Observatori: json.keperawatan_observatori && json.keperawatan_observatori === '1' ? 1 : 0,
          Lain: json.keperawatan_metode_pembelajaran_lain && json.keperawatan_metode_pembelajaran_lain === '1' ? 1 : 0,
          Lain_Teks: json.keperawatan_metode_pembelajaran_lain_teks ?? '',
        },
        Evaluasi_Pasien: {
          Mampu_Memahami: json.keperawatan_mampu_memahami && json.keperawatan_mampu_memahami === '1' ? 1 : 0,
          Mampu_Mengerti: json.keperawatan_mampu_mengerti && json.keperawatan_mampu_mengerti === '1' ? 1 : 0,
          Lain: json.keperawatan_evaluasi_pasien_lain && json.keperawatan_evaluasi_pasien_lain === '1' ? 1 : 0,
          Lain_Teks: json.keperawatan_evaluasi_pasien_lain_teks ?? '',
        },
        Waktu_Edukasi: json.keperawatan_waktu_edukasi ?? '',
        Durasi: json.keperawatan_durasi ?? '',
        Penerima_Edukasi: {
          Pasien: json.keperawatan_pasien && json.keperawatan_pasien === '1' ? 1 : 0,
          Pasangan: json.keperawatan_pasangan && json.keperawatan_pasangan === '1' ? 1 : 0,
          Orang_Tua: json.keperawatan_orang_tua && json.keperawatan_orang_tua === '1' ? 1 : 0,
          Saudara_Kandung: json.keperawatan_saudara_kandung && json.keperawatan_saudara_kandung === '1' ? 1 : 0,
          Lain: json.keperawatan_penerima_edukasi_lain && json.keperawatan_penerima_edukasi_lain === '1' ? 1 : 0,
          Lain_Teks: json.keperawatan_evaluasi_pasien_lain_teks ?? '',
        },
      },
      Farmasi: {
        Metode_Pembelajaran: {
          Diskusi: json.farmasi_diskusi && json.farmasi_diskusi === '1' ? 1 : 0,
          Demonstrasi: json.farmasi_demonstrasi && json.farmasi_demonstrasi === '1' ? 1 : 0,
          Ceramah: json.farmasi_ceramah && json.farmasi_ceramah === '1' ? 1 : 0,
          Solusi: json.farmasi_solusi && json.farmasi_solusi === '1' ? 1 : 0,
          Observatori: json.farmasi_observatori && json.farmasi_observatori === '1' ? 1 : 0,
          Lain: json.farmasi_metode_pembelajaran_lain && json.farmasi_metode_pembelajaran_lain === '1' ? 1 : 0,
          Lain_Teks: json.farmasi_metode_pembelajaran_lain_teks ?? '',
        },
        Evaluasi_Pasien: {
          Mampu_Memahami: json.farmasi_mampu_memahami && json.farmasi_mampu_memahami === '1' ? 1 : 0,
          Mampu_Mengerti: json.farmasi_mampu_mengerti && json.farmasi_mampu_mengerti === '1' ? 1 : 0,
          Lain: json.farmasi_evaluasi_pasien_lain && json.farmasi_evaluasi_pasien_lain === '1' ? 1 : 0,
          Lain_Teks: json.farmasi_evaluasi_pasien_lain_teks ?? '',
        },
        Waktu_Edukasi: json.farmasi_waktu_edukasi ?? '',
        Durasi: json.farmasi_durasi ?? '',
        Penerima_Edukasi: {
          Pasien: json.farmasi_pasien && json.farmasi_pasien === '1' ? 1 : 0,
          Pasangan: json.farmasi_pasangan && json.farmasi_pasangan === '1' ? 1 : 0,
          Orang_Tua: json.farmasi_orang_tua && json.farmasi_orang_tua === '1' ? 1 : 0,
          Saudara_Kandung: json.farmasi_saudara_kandung && json.farmasi_saudara_kandung === '1' ? 1 : 0,
          Lain: json.farmasi_penerima_edukasi_lain && json.farmasi_penerima_edukasi_lain === '1' ? 1 : 0,
          Lain_Teks: json.farmasi_evaluasi_pasien_lain_teks ?? '',
        },
      },
      Dokter: {
        Metode_Pembelajaran: {
          Diskusi: json.dokter_diskusi && json.dokter_diskusi === '1' ? 1 : 0,
          Demonstrasi: json.dokter_demonstrasi && json.dokter_demonstrasi === '1' ? 1 : 0,
          Ceramah: json.dokter_ceramah && json.dokter_ceramah === '1' ? 1 : 0,
          Solusi: json.dokter_solusi && json.dokter_solusi === '1' ? 1 : 0,
          Observatori: json.dokter_observatori && json.dokter_observatori === '1' ? 1 : 0,
          Lain: json.dokter_metode_pembelajaran_lain && json.dokter_metode_pembelajaran_lain === '1' ? 1 : 0,
          Lain_Teks: json.dokter_metode_pembelajaran_lain_teks ?? '',
        },
        Evaluasi_Pasien: {
          Mampu_Memahami: json.dokter_mampu_memahami && json.dokter_mampu_memahami === '1' ? 1 : 0,
          Mampu_Mengerti: json.dokter_mampu_mengerti && json.dokter_mampu_mengerti === '1' ? 1 : 0,
          Lain: json.dokter_evaluasi_pasien_lain && json.dokter_evaluasi_pasien_lain === '1' ? 1 : 0,
          Lain_Teks: json.dokter_evaluasi_pasien_lain_teks ?? '',
        },
        Waktu_Edukasi: json.dokter_waktu_edukasi ?? '',
        Durasi: json.dokter_durasi ?? '',
        Penerima_Edukasi: {
          Pasien: json.dokter_pasien && json.dokter_pasien === '1' ? 1 : 0,
          Pasangan: json.dokter_pasangan && json.dokter_pasangan === '1' ? 1 : 0,
          Orang_Tua: json.dokter_orang_tua && json.dokter_orang_tua === '1' ? 1 : 0,
          Saudara_Kandung: json.dokter_saudara_kandung && json.dokter_saudara_kandung === '1' ? 1 : 0,
          Lain: json.dokter_penerima_edukasi_lain && json.dokter_penerima_edukasi_lain === '1' ? 1 : 0,
          Lain_Teks: json.dokter_penerima_edukasi_lain_teks ?? '',
        },
      },
      Rohaniawan: {
        Metode_Pembelajaran: {
          Diskusi: json.rohaniawan_diskusi && json.rohaniawan_diskusi === '1' ? 1 : 0,
          Demonstrasi: json.rohaniawan_demonstrasi && json.rohaniawan_demonstrasi === '1' ? 1 : 0,
          Ceramah: json.rohaniawan_ceramah && json.rohaniawan_ceramah === '1' ? 1 : 0,
          Solusi: json.rohaniawan_solusi && json.rohaniawan_solusi === '1' ? 1 : 0,
          Observatori: json.rohaniawan_observatori && json.rohaniawan_observatori === '1' ? 1 : 0,
          Lain: json.rohaniawan_metode_pembelajaran_lain && json.rohaniawan_metode_pembelajaran_lain === '1' ? 1 : 0,
          Lain_Teks: json.rohaniawan_metode_pembelajaran_lain_teks ?? '',
        },
        Evaluasi_Pasien: {
          Mampu_Memahami: json.rohaniawan_mampu_memahami && json.rohaniawan_mampu_memahami === '1' ? 1 : 0,
          Mampu_Mengerti: json.rohaniawan_mampu_mengerti && json.rohaniawan_mampu_mengerti === '1' ? 1 : 0,
          Lain: json.rohaniawan_evaluasi_pasien_lain && json.rohaniawan_evaluasi_pasien_lain === '1' ? 1 : 0,
          Lain_Teks: json.rohaniawan_evaluasi_pasien_lain_teks ?? '',
        },
        Waktu_Edukasi: json.rohaniawan_waktu_edukasi ?? '',
        Durasi: json.rohaniawan_durasi ?? '',
        Penerima_Edukasi: {
          Pasien: json.rohaniawan_pasien && json.rohaniawan_pasien === '1' ? 1 : 0,
          Pasangan: json.rohaniawan_pasangan && json.rohaniawan_pasangan === '1' ? 1 : 0,
          Orang_Tua: json.rohaniawan_orang_tua && json.rohaniawan_orang_tua === '1' ? 1 : 0,
          Saudara_Kandung: json.rohaniawan_saudara_kandung && json.rohaniawan_saudara_kandung === '1' ? 1 : 0,
          Lain: json.rohaniawan_penerima_edukasi_lain && json.rohaniawan_penerima_edukasi_lain === '1' ? 1 : 0,
          Lain_Teks: json.rohaniawan_evaluasi_pasien_lain_teks ?? '',
        },
      },
      Mencuci_Tangan: {
        Metode_Pembelajaran: {
          Diskusi: json.mencuci_tangan_diskusi && json.mencuci_tangan_diskusi === '1' ? 1 : 0,
          Demonstrasi: json.mencuci_tangan_demonstrasi && json.mencuci_tangan_demonstrasi === '1' ? 1 : 0,
          Ceramah: json.mencuci_tangan_ceramah && json.mencuci_tangan_ceramah === '1' ? 1 : 0,
          Solusi: json.mencuci_tangan_solusi && json.mencuci_tangan_solusi === '1' ? 1 : 0,
          Observatori: json.mencuci_tangan_observatori && json.mencuci_tangan_observatori === '1' ? 1 : 0,
          Lain: json.mencuci_tangan_metode_pembelajaran_lain && json.mencuci_tangan_metode_pembelajaran_lain === '1' ? 1 : 0,
          Lain_Teks: json.mencuci_tangan_metode_pembelajaran_lain_teks ?? '',
        },
        Evaluasi_Pasien: {
          Mampu_Memahami: json.mencuci_tangan_mampu_memahami && json.mencuci_tangan_mampu_memahami === '1' ? 1 : 0,
          Mampu_Mengerti: json.mencuci_tangan_mampu_mengerti && json.mencuci_tangan_mampu_mengerti === '1' ? 1 : 0,
          Lain: json.mencuci_tangan_evaluasi_pasien_lain && json.mencuci_tangan_evaluasi_pasien_lain === '1' ? 1 : 0,
          Lain_Teks: json.mencuci_tangan_evaluasi_pasien_lain_teks ?? '',
        },
        Waktu_Edukasi: json.mencuci_tangan_waktu_edukasi ?? '',
        Durasi: json.mencuci_tangan_durasi ?? '',
        Penerima_Edukasi: {
          Pasien: json.mencuci_tangan_pasien && json.mencuci_tangan_pasien === '1' ? 1 : 0,
          Pasangan: json.mencuci_tangan_pasangan && json.mencuci_tangan_pasangan === '1' ? 1 : 0,
          Orang_Tua: json.mencuci_tangan_orang_tua && json.mencuci_tangan_orang_tua === '1' ? 1 : 0,
          Saudara_Kandung: json.mencuci_tangan_saudara_kandung && json.mencuci_tangan_saudara_kandung === '1' ? 1 : 0,
          Lain: json.mencuci_tangan_penerima_edukasi_lain && json.mencuci_tangan_penerima_edukasi_lain === '1' ? 1 : 0,
          Lain_Teks: json.mencuci_tangan_evaluasi_pasien_lain_teks ?? '',
        },
      },
      Penggunaan_Peralatan: {
        Metode_Pembelajaran: {
          Diskusi: json.penggunaan_peralatan_diskusi && json.penggunaan_peralatan_diskusi === '1' ? 1 : 0,
          Demonstrasi: json.penggunaan_peralatan_demonstrasi && json.penggunaan_peralatan_demonstrasi === '1' ? 1 : 0,
          Ceramah: json.penggunaan_peralatan_ceramah && json.penggunaan_peralatan_ceramah === '1' ? 1 : 0,
          Solusi: json.penggunaan_peralatan_solusi && json.penggunaan_peralatan_solusi === '1' ? 1 : 0,
          Observatori: json.penggunaan_peralatan_observatori && json.penggunaan_peralatan_observatori === '1' ? 1 : 0,
          Lain: json.penggunaan_peralatan_metode_pembelajaran_lain && json.penggunaan_peralatan_metode_pembelajaran_lain === '1' ? 1 : 0,
          Lain_Teks: json.penggunaan_peralatan_metode_pembelajaran_lain_teks ?? '',
        },
        Evaluasi_Pasien: {
          Mampu_Memahami: json.penggunaan_peralatan_mampu_memahami && json.penggunaan_peralatan_mampu_memahami === '1' ? 1 : 0,
          Mampu_Mengerti: json.penggunaan_peralatan_mampu_mengerti && json.penggunaan_peralatan_mampu_mengerti === '1' ? 1 : 0,
          Lain: json.penggunaan_peralatan_evaluasi_pasien_lain && json.penggunaan_peralatan_evaluasi_pasien_lain === '1' ? 1 : 0,
          Lain_Teks: json.penggunaan_peralatan_evaluasi_pasien_lain_teks ?? '',
        },
        Waktu_Edukasi: json.penggunaan_peralatan_waktu_edukasi ?? '',
        Durasi: json.penggunaan_peralatan_durasi ?? '',
        Penerima_Edukasi: {
          Pasien: json.penggunaan_peralatan_pasien && json.penggunaan_peralatan_pasien === '1' ? 1 : 0,
          Pasangan: json.penggunaan_peralatan_pasangan && json.penggunaan_peralatan_pasangan === '1' ? 1 : 0,
          Orang_Tua: json.penggunaan_peralatan_orang_tua && json.penggunaan_peralatan_orang_tua === '1' ? 1 : 0,
          Saudara_Kandung: json.penggunaan_peralatan_saudara_kandung && json.penggunaan_peralatan_saudara_kandung === '1' ? 1 : 0,
          Lain: json.penggunaan_peralatan_penerima_edukasi_lain && json.penggunaan_peralatan_penerima_edukasi_lain === '1' ? 1 : 0,
          Lain_Teks: json.penggunaan_peralatan_evaluasi_pasien_lain_teks ?? '',
        },
      },
      Hak_Kewajiban: {
        Metode_Pembelajaran: {
          Diskusi: json.hak_kewajiban_diskusi && json.hak_kewajiban_diskusi === '1' ? 1 : 0,
          Demonstrasi: json.hak_kewajiban_demonstrasi && json.hak_kewajiban_demonstrasi === '1' ? 1 : 0,
          Ceramah: json.hak_kewajiban_ceramah && json.hak_kewajiban_ceramah === '1' ? 1 : 0,
          Solusi: json.hak_kewajiban_solusi && json.hak_kewajiban_solusi === '1' ? 1 : 0,
          Observatori: json.hak_kewajiban_observatori && json.hak_kewajiban_observatori === '1' ? 1 : 0,
          Lain: json.hak_kewajiban_metode_pembelajaran_lain && json.hak_kewajiban_metode_pembelajaran_lain === '1' ? 1 : 0,
          Lain_Teks: json.hak_kewajiban_metode_pembelajaran_lain_teks ?? '',
        },
        Evaluasi_Pasien: {
          Mampu_Memahami: json.hak_kewajiban_mampu_memahami && json.hak_kewajiban_mampu_memahami === '1' ? 1 : 0,
          Mampu_Mengerti: json.hak_kewajiban_mampu_mengerti && json.hak_kewajiban_mampu_mengerti === '1' ? 1 : 0,
          Lain: json.hak_kewajiban_evaluasi_pasien_lain && json.hak_kewajiban_evaluasi_pasien_lain === '1' ? 1 : 0,
          Lain_Teks: json.hak_kewajiban_evaluasi_pasien_lain_teks ?? '',
        },
        Waktu_Edukasi: json.hak_kewajiban_waktu_edukasi ?? '',
        Durasi: json.hak_kewajiban_durasi ?? '',
        Penerima_Edukasi: {
          Pasien: json.hak_kewajiban_pasien && json.hak_kewajiban_pasien === '1' ? 1 : 0,
          Pasangan: json.hak_kewajiban_pasangan && json.hak_kewajiban_pasangan === '1' ? 1 : 0,
          Orang_Tua: json.hak_kewajiban_orang_tua && json.hak_kewajiban_orang_tua === '1' ? 1 : 0,
          Saudara_Kandung: json.hak_kewajiban_saudara_kandung && json.hak_kewajiban_saudara_kandung === '1' ? 1 : 0,
          Lain: json.hak_kewajiban_penerima_edukasi_lain && json.hak_kewajiban_penerima_edukasi_lain === '1' ? 1 : 0,
          Lain_Teks: json.hak_kewajiban_evaluasi_pasien_lain_teks ?? '',
        },
      },
      Informasi_Lain: {
        Metode_Pembelajaran: {
          Diskusi: json.informasi_lain_diskusi && json.informasi_lain_diskusi === '1' ? 1 : 0,
          Demonstrasi: json.informasi_lain_demonstrasi && json.informasi_lain_demonstrasi === '1' ? 1 : 0,
          Ceramah: json.informasi_lain_ceramah && json.informasi_lain_ceramah === '1' ? 1 : 0,
          Solusi: json.informasi_lain_solusi && json.informasi_lain_solusi === '1' ? 1 : 0,
          Observatori: json.informasi_lain_observatori && json.informasi_lain_observatori === '1' ? 1 : 0,
          Lain: json.informasi_lain_metode_pembelajaran_lain && json.informasi_lain_metode_pembelajaran_lain === '1' ? 1 : 0,
          Lain_Teks: json.informasi_lain_metode_pembelajaran_lain_teks ?? '',
        },
        Evaluasi_Pasien: {
          Mampu_Memahami: json.informasi_lain_mampu_memahami && json.informasi_lain_mampu_memahami === '1' ? 1 : 0,
          Mampu_Mengerti: json.informasi_lain_mampu_mengerti && json.informasi_lain_mampu_mengerti === '1' ? 1 : 0,
          Lain: json.informasi_lain_evaluasi_pasien_lain && json.informasi_lain_evaluasi_pasien_lain === '1' ? 1 : 0,
          Lain_Teks: json.informasi_lain_evaluasi_pasien_lain_teks ?? '',
        },
        Waktu_Edukasi: json.informasi_lain_waktu_edukasi ?? '',
        Durasi: json.informasi_lain_durasi ?? '',
        Penerima_Edukasi: {
          Pasien: json.informasi_lain_pasien && json.informasi_lain_pasien === '1' ? 1 : 0,
          Pasangan: json.informasi_lain_pasangan && json.informasi_lain_pasangan === '1' ? 1 : 0,
          Orang_Tua: json.informasi_lain_orang_tua && json.informasi_lain_orang_tua === '1' ? 1 : 0,
          Saudara_Kandung: json.informasi_lain_saudara_kandung && json.informasi_lain_saudara_kandung === '1' ? 1 : 0,
          Lain: json.informasi_lain_penerima_edukasi_lain && json.informasi_lain_penerima_edukasi_lain === '1' ? 1 : 0,
          Lain_Teks: json.informasi_lain_evaluasi_pasien_lain_teks ?? '',
        },
      },
      Asesmen: {
        Tidak_Ada: assessments[1],
        Penglihatan_Terganggu: assessments[2],
        Pendengaran_Kurang: assessments[3],
        Tidak_Berbahasa_Indonesia: assessments[4],
        Keyakinan: assessments[5],
        Agama: assessments[6],
        Kongnisi_Terbatas: assessments[7],
        Hambatan_Emosi: assessments[8],
        Pertimbangan_Budaya: assessments[9],
        Tingkat_Pendidikan: assessments[10],
        Nilai_Nilai: assessments[11],
      },
      Materi_Edukasi_Id: json.materi_edukasi ?? '',
      Informasi_Lain_Pasien: json.daftar_pasien_informasi_lain ?? [],
      Materi_Edukasi_Penjelasan: {
        DPJP: {
          Kondisi_Pasien: json.dpjp_kondisi_pasien && json.dpjp_kondisi_pasien === '1' ? 1 : 0,
          Hasil_Pemeriksaan: json.dpjp_hasil_pemeriksaan && json.dpjp_hasil_pemeriksaan === '1' ? 1 : 0,
          Pengobatan: json.dpjp_pengobatan && json.dpjp_pengobatan === '1' ? 1 : 0,
          Manfaat: json.dpjp_manfaat && json.dpjp_manfaat === '1' ? 1 : 0,
          Alternatif: json.dpjp_alternatif && json.dpjp_alternatif === '1' ? 1 : 0,
          Keberhasilan: json.dpjp_keberhasilan && json.dpjp_keberhasilan === '1' ? 1 : 0,
          Pemulihan: json.dpjp_pemulihan && json.dpjp_pemulihan === '1' ? 1 : 0,
          Diagnosa: json.dpjp_diagnosa && json.dpjp_diagnosa === '1' ? 1 : 0,
          Hasil_Asuhan: json.dpjp_hasil_asuhan && json.dpjp_hasil_asuhan === '1' ? 1 : 0,
          Hasil_Asuhan_Teks: json.dpjp_hasil_asuhan_teks ?? '',
          Hasil_Asuhan_Teks_2: json.dpjp_hasil_asuhan_teks_2 ?? '',
          Diagnosa_Teks: json.dpjp_diagnosa_teks ?? '',
          Diagnosa_Teks_1: json.dpjp_diagnosa_teks_1 ?? '',
          Diagnosa_Teks_2: json.dpjp_diagnosa_teks_2 ?? '',
        },
        Gizi: {
          Diluar_RS: json.gizi_diluar_rs && json.gizi_diluar_rs === '1' ? 1 : 0,
          Lain_Lain: json.gizi_lain_lain && json.gizi_lain_lain === '1' ? 1 : 0,
          Status_Gizi: json.gizi_status_gizi && json.gizi_status_gizi === '1' ? 1 : 0,
          Untuk_Dirumah: json.gizi_untuk_dirumah && json.gizi_untuk_dirumah === '1' ? 1 : 0,
          Lain_Lain_Teks: json.gizi_lain_lain_teks ?? '',
          Selama_Perawatan: json.gizi_selama_perawatan && json.gizi_selama_perawatan === '1' ? 1 : 0,
        },
        Manajemen_Nyeri: {
          Farmakologi: json.manajemen_nyeri_farmakologi && json.manajemen_nyeri_farmakologi === '1' ? 1 : 0,
          Non_Farmakologi: json.manajemen_nyeri_non_farmakologi && json.manajemen_nyeri_non_farmakologi === '1' ? 1 : 0,
        },
        Post_Operasi: {
          Merunduk: json.post_op_merunduk && json.post_op_merunduk === '1' ? 1 : 0,
          Setengah_Duduk: json.post_op_setengah_duduk && json.post_op_setengah_duduk === '1' ? 1 : 0,
          Tidak_Ada: json.post_op_tidak_ada && json.post_op_tidak_ada === '1' ? 1 : 0,
        },
        Keperawatan: {
          Mobilisasi: json.keperawatan_mobilisasi && json.keperawatan_mobilisasi === '1' ? 1 : 0,
          Perawatan_Luka: json.keperawatan_perawatan_luka && json.keperawatan_perawatan_luka === '1' ? 1 : 0,
          Perawatan_Peralatan_Medis: json.keperawatan_perawatan_peralatan && json.keperawatan_perawatan_peralatan === '1' ? 1 : 0,
          Pemberian_Makan: json.keperawatan_pemberian_makan && json.keperawatan_pemberian_makan === '1' ? 1 : 0,
          Membuang_Urine: json.keperawatan_membuang_urine && json.keperawatan_membuang_urine === '1' ? 1 : 0,
          Lain_Lain: json.keperawatan_lain_lain && json.keperawatan_lain_lain === '1' ? 1 : 0,
          Lain_Lain_Teks: json.keperawatan_lain_lain_teks ?? '',
        },
        Farmasi: {
          Lain_Lain: json.farmasi_lain_lain && json.farmasi_lain_lain === '1' ? 1 : 0,
          Efek_Samping: json.farmasi_efek_samping && json.farmasi_efek_samping === '1' ? 1 : 0,
          Lain_Lain_Teks: json.farmasi_lain_lain_teks ?? '',
          Penggunaan_Obat: json.farmasi_penggunaan_obat && json.farmasi_penggunaan_obat === '1' ? 1 : 0,
          Mencegah_Interaksi: json.farmasi_mencegah_interaksi && json.farmasi_mencegah_interaksi === '1' ? 1 : 0,
        },
        Dokter: {
          Kondisi_Pasien: json.dokter_kondisi_pasien && json.dokter_kondisi_pasien === '1' ? 1 : 0,
          Hasil_Pemeriksaan: json.dokter_hasil_pemeriksaan && json.dokter_hasil_pemeriksaan === '1' ? 1 : 0,
          Teknik_Anestesi: json.dokter_teknik_anestesi && json.dokter_teknik_anestesi === '1' ? 1 : 0,
          Manfaat: json.dokter_manfaat_kekurangan && json.dokter_manfaat_kekurangan === '1' ? 1 : 0,
          Nyeri_Pasca: json.dokter_nyeri_pasca && json.dokter_nyeri_pasca === '1' ? 1 : 0,
          Analgesi_Pasca: json.dokter_nyeri_analgesi && json.dokter_nyeri_analgesi === '1' ? 1 : 0,
        },
        Rohaniawan: {
          Bimbingan: json.rohaniawan_bimbingan && json.rohaniawan_bimbingan === '1' ? 1 : 0,
          Konseling: json.rohaniawan_konseling && json.rohaniawan_konseling === '1' ? 1 : 0,
        },
        Mencuci_Tangan: {
          Handwash_4060: json.mencuci_tangan_handwash && json.mencuci_tangan_handwash === '1' ? 1 : 0,
          Handrub_2030: json.mencuci_tangan_handrub && json.mencuci_tangan_handrub === '1' ? 1 : 0,
        },
        Penggunaan_Peralatan: {
          Infus: json.penggunaan_peralatan_infus && json.penggunaan_peralatan_infus === '1' ? 1 : 0,
          Oksigen: json.penggunaan_peralatan_oksigen && json.penggunaan_peralatan_oksigen === '1' ? 1 : 0,
          Nebulizer: json.penggunaan_peralatan_nebulizer && json.penggunaan_peralatan_nebulizer === '1' ? 1 : 0,
          Lain_Lain: json.penggunaan_peralatan_lain && json.penggunaan_peralatan_lain === '1' ? 1 : 0,
          Lain_Lain_Teks: json.penggunaan_peralatan_lain_teks ?? '',
        },
        Hak_Kewajiban: {
          Hak_Pasien: json.hak_kewajiban_hak_pasien && json.hak_kewajiban_hak_pasien === '1' ? 1 : 0,
          Kewajiban_Pasien: json.hak_kewajiban_kewajiban_pasien && json.hak_kewajiban_kewajiban_pasien === '1' ? 1 : 0,
        },
      },
    }
  }
}

